import {newLayer,draw,hit,clamp,exportName} from './renderer.js';
const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d');
let pages=[],current=-1,selected=null,busy=false,drag=null;
const page=()=>pages[current],layer=()=>page()?.layers.find(l=>l.id===selected);
const fields=['text','kind','shape','x','y','w','h','size','rotation','vertical','color','fill','tailX','tailY'];
const status=t=>$('status').textContent=t;
function checkpoint(){const p=page();p.undo.push(JSON.stringify(p.layers));if(p.undo.length>100)p.undo.shift();p.redo=[];}
function render(){const p=page();$('empty').hidden=!!p;canvas.hidden=!p;if(p){if(canvas.width!==p.img.width||canvas.height!==p.img.height){canvas.width=p.img.width;canvas.height=p.img.height;}draw(ctx,p.img,p.layers,selected);}$('filename').textContent=p?`${p.name} · ${p.img.width} × ${p.img.height}`:'画像を選択';$('count').textContent=`${pages.length} 枚`;for(const id of ['bubble','sfx','remove'])$(id).disabled=!p||busy;$('delete').disabled=!p?.directory||busy;$('save').disabled=!pages.length||busy;$('undo').disabled=!p?.undo.length||busy;$('redo').disabled=!p?.redo.length||busy;}
function list(){const container=$('images');container.replaceChildren();pages.forEach((p,i)=>{const b=document.createElement('button');b.className='thumb'+(current===i?' active':'');const im=document.createElement('img');im.src=p.src;im.alt='';const text=document.createElement('span');text.textContent=p.name;b.append(im,text);b.onclick=()=>{current=i;selected=null;refresh();};container.append(b);});}
function properties(){const p=page(),l=layer();$('properties').hidden=!l;$('layers').replaceChildren();for(const item of p?.layers||[]){const b=document.createElement('button');b.textContent=`${item.kind==='bubble'?'◯':'✦'} ${item.text||'（空の文字）'}`;b.className=item.id===selected?'active':'';b.onclick=()=>{selected=item.id;properties();render();};$('layers').append(b);}if(!l)return;for(const f of fields)$(f).value=String(l[f]);$('swapTarget').replaceChildren();for(const item of p.layers.filter(i=>i.id!==l.id)){const o=document.createElement('option');o.value=item.id;o.textContent=item.text||'（空の文字）';$('swapTarget').append(o);}$('swap').disabled=p.layers.length<2;}
function refresh(){list();properties();render();}
async function guard(fn){if(busy)return;busy=true;render();try{await fn();}catch(e){if(e.name!=='AbortError'){console.error(e);status(`処理できなかった: ${e.message}`);}}finally{busy=false;render();}}
function decode(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('画像を読み込めない'));im.src=src;});}
function dataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
async function addFiles(entries){let failures=0;for(const {file,directory=null} of entries){if(!/\.(png|jpe?g|webp|gif|avif)$/i.test(file.name))continue;const src=URL.createObjectURL(file);try{const img=await decode(src);pages.push({name:file.name,src,img,file,directory,layers:[],undo:[],redo:[]});}catch{URL.revokeObjectURL(src);failures++;}}if(current<0&&pages.length)current=0;refresh();status(`${pages.length} 枚を表示${failures?` · ${failures} 枚は読込失敗`:''}`);}
$('open').onclick=()=>guard(async()=>{if(!window.showDirectoryPicker){status('フォルダ直接操作はPC版Chrome / Edgeで利用可能。「画像を追加」で複数画像を編集できる。');return;}const dir=await window.showDirectoryPicker({mode:'readwrite'});const entries=[];for await(const h of dir.values())if(h.kind==='file')entries.push({file:await h.getFile(),directory:dir});entries.sort((a,b)=>a.file.name.localeCompare(b.file.name,'ja',{numeric:true}));await addFiles(entries);});
$('files').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>guard(async()=>{await addFiles([...e.target.files].map(file=>({file})));e.target.value='';});
for(const kind of ['bubble','sfx'])$(kind).onclick=()=>{if(!page())return;checkpoint();const l=newLayer(kind,canvas.width,canvas.height);page().layers.push(l);selected=l.id;properties();render();};
for(const f of fields){$(f).addEventListener('focus',()=>{if(layer())checkpoint();});$(f).addEventListener('input',()=>{const l=layer();if(!l)return;let v=$(f).value;if(['x','y','w','h','size','rotation','tailX','tailY'].includes(f)){if(v===''||!Number.isFinite(Number(v)))return;v=Number(v);if(['w','h'].includes(f))v=clamp(v,30,30000);if(f==='size')v=clamp(v,8,500);if(f==='rotation')v=clamp(v,-180,180);}if(f==='vertical')v=v==='true';l[f]=v;render();});$(f).addEventListener('change',()=>properties());}
function mutate(fn){if(!layer())return;checkpoint();fn(page(),layer());properties();render();}
$('duplicate').onclick=()=>mutate((p,l)=>{const copy={...l,id:crypto.randomUUID(),x:l.x+20,y:l.y+20};p.layers.push(copy);selected=copy.id;});
$('dropLayer').onclick=()=>mutate((p,l)=>{p.layers=p.layers.filter(i=>i!==l);selected=null;});
for(const [id,delta] of [['backward',-1],['forward',1]])$(id).onclick=()=>mutate((p,l)=>{const i=p.layers.indexOf(l),j=clamp(i+delta,0,p.layers.length-1);[p.layers[i],p.layers[j]]=[p.layers[j],p.layers[i]];});
$('swap').onclick=()=>mutate((p,l)=>{const other=p.layers.find(i=>i.id===$('swapTarget').value);if(other)[l.text,other.text]=[other.text,l.text];});
for(const [id,from,to] of [['undo','undo','redo'],['redo','redo','undo']])$(id).onclick=()=>{const p=page();if(!p?.[from].length)return;p[to].push(JSON.stringify(p.layers));p.layers=JSON.parse(p[from].pop());selected=null;properties();render();};
function coords(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};}
canvas.onpointerdown=e=>{if(busy)return;const pos=coords(e),l=[...page().layers].reverse().find(l=>hit(l,pos.x,pos.y));selected=l?.id||null;if(l){checkpoint();drag={id:e.pointerId,dx:pos.x-l.x,dy:pos.y-l.y};canvas.setPointerCapture(e.pointerId);}properties();render();};
canvas.onpointermove=e=>{if(!drag||!layer())return;const pos=coords(e);layer().x=Math.round(pos.x-drag.dx);layer().y=Math.round(pos.y-drag.dy);render();};
canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;properties();};
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||busy)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$(e.shiftKey?'redo':'undo').click();return;}const dir={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(dir&&layer()){e.preventDefault();mutate((p,l)=>{l.x+=dir[0]*(e.shiftKey?10:1);l.y+=dir[1]*(e.shiftKey?10:1);});}});
function removeCurrent(){const [p]=pages.splice(current,1);if(p.src.startsWith('blob:'))URL.revokeObjectURL(p.src);current=Math.min(current,pages.length-1);selected=null;refresh();}
$('remove').onclick=()=>{if(!page())return;if(page().layers.length&&!confirm(`「${page().name}」を一覧から外す？ 未保存の編集は失われる。元ファイルは残る。`))return;removeCurrent();};
$('delete').onclick=()=>guard(async()=>{const p=page();if(!p?.directory)return;if(!confirm(`元画像「${p.name}」をフォルダから完全に削除する？\nゴミ箱には移動しない。保存していない編集も失われる。`))return;await p.directory.removeEntry(p.name);removeCurrent();status('元画像を削除した');});
async function write(dir,name,data){const h=await dir.getFileHandle(name,{create:true});const writer=await h.createWritable();try{await writer.write(data);await writer.close();}catch(e){await writer.abort().catch(()=>{});throw e;}}
async function projectData(snapshot=pages){return {version:1,pages:await Promise.all(snapshot.map(async p=>({name:p.name,src:p.src.startsWith('data:')?p.src:await dataURL(p.file),layers:p.layers})))};}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('save').onclick=()=>guard(async()=>{if(!window.showDirectoryPicker){status('新規フォルダへの一括保存はPC版Chrome / Edgeで利用可能。編集データ保存で作業を持ち出せる。');return;}const parent=await window.showDirectoryPicker({mode:'readwrite'});const folder=`serifu_${new Date().toISOString().replace(/[:.]/g,'-')}_${crypto.randomUUID().slice(0,8)}`;const dir=await parent.getDirectoryHandle(folder,{create:true});const snapshot=pages.map(p=>({...p,layers:structuredClone(p.layers)}));let completed=0;try{for(const [i,p] of snapshot.entries()){status(`保存中 ${i+1} / ${snapshot.length} 枚`);const c=document.createElement('canvas');c.width=p.img.width;c.height=p.img.height;draw(c.getContext('2d'),p.img,p.layers);const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw new Error('PNG生成に失敗');await write(dir,exportName(p.name,i),blob);completed++;}await write(dir,'serifu-project.json',JSON.stringify(await projectData(snapshot)));status(`${snapshot.length} 枚と編集データを「${folder}」へ保存した`);}catch(e){throw new Error(`${folder} 内に ${completed} 枚保存済み。${e.message}`);}});
$('projectSave').onclick=()=>guard(async()=>{if(!pages.length)return;download(new Blob([JSON.stringify(await projectData())],{type:'application/json'}),'serifu-project.json');status('編集データを保存した');});
$('projectLoad').onclick=()=>$('projectInput').click();
function validateLayer(l){if(!l||!['bubble','sfx'].includes(l.kind)||typeof l.text!=='string'||!['ellipse','rect'].includes(l.shape)||typeof l.vertical!=='boolean')throw new Error('編集データの文字設定が不正');for(const key of ['x','y','w','h','size','rotation','tailX','tailY'])if(!Number.isFinite(l[key]))throw new Error('座標が不正');if(l.w<30||l.h<30||l.size<8||l.size>500)throw new Error('サイズが不正');for(const key of ['color','fill'])if(!/^#[0-9a-f]{6}$/i.test(l[key]))throw new Error('色が不正');return {...l,id:crypto.randomUUID()};}
$('projectInput').onchange=e=>{const file=e.target.files[0];e.target.value='';if(!file)return;guard(async()=>{const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.pages))throw new Error('未対応の編集データ');const loaded=[];for(const p of data.pages){if(typeof p.name!=='string'||typeof p.src!=='string'||!/^data:image\/(png|jpeg|webp|gif|avif);base64,/.test(p.src)||!Array.isArray(p.layers))throw new Error('画像データが不正');loaded.push({name:p.name,src:p.src,img:await decode(p.src),layers:p.layers.map(validateLayer),undo:[],redo:[],directory:null});}pages.push(...loaded);current=pages.length-loaded.length;selected=null;refresh();status('編集データを追加した。元ファイルとの接続はないため、元画像削除は無効。');});};
$('demo').onclick=()=>guard(async()=>{const c=document.createElement('canvas');c.width=1000;c.height=750;const cx=c.getContext('2d'),g=cx.createLinearGradient(0,0,1000,750);g.addColorStop(0,'#657d76');g.addColorStop(1,'#d6b993');cx.fillStyle=g;cx.fillRect(0,0,1000,750);cx.fillStyle='#304743';cx.beginPath();cx.moveTo(0,600);cx.lineTo(280,220);cx.lineTo(630,750);cx.lineTo(0,750);cx.fill();cx.fillStyle='#526257';cx.beginPath();cx.moveTo(300,750);cx.lineTo(740,290);cx.lineTo(1000,600);cx.lineTo(1000,750);cx.fill();cx.fillStyle='#ffe5ac';cx.beginPath();cx.arc(780,160,65,0,Math.PI*2);cx.fill();const src=c.toDataURL();const l=newLayer('bubble',1000,750);l.x=300;l.y=180;l.text='さあ、\n物語を始めよう。';const s=newLayer('sfx',1000,750);s.x=750;s.y=560;s.text='ザァァ…';s.rotation=-12;pages.push({name:'sample.png',src,img:await decode(src),layers:[l,s],undo:[],redo:[]});current=pages.length-1;selected=l.id;refresh();});
window.addEventListener('beforeunload',e=>{if(pages.length){e.preventDefault();e.returnValue='';}});refresh();
