import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir,writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
const port=5189,server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','pipe']});
let browser,page;
try {
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Test server did not start')),10000);server.stdout.once('data',()=>{clearTimeout(timer);resolve();});server.once('error',reject);server.stderr.on('data',chunk=>process.stderr.write(chunk));});
  browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.clock.install();
  await page.goto(`http://127.0.0.1:${port}`);
  assert.equal(await page.locator('#saveEdited').evaluate(button=>button.previousElementSibling.id),'save');
  const images=await page.evaluate(()=>[[1000,750],[1000,750],[500,1000]].map(([width,height])=>{
    const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;
    const context=canvas.getContext('2d'),gradient=context.createLinearGradient(0,0,width,height);gradient.addColorStop(0,'#24463a');gradient.addColorStop(1,'#78a15b');context.fillStyle=gradient;context.fillRect(0,0,width,height);
    return canvas.toDataURL().split(',')[1];
  }));
  await page.locator('#fileInput').setInputFiles(images.map((image,i)=>({name:['01-source.png','02-untouched.png','03-portrait.png'][i],mimeType:'image/png',buffer:Buffer.from(image,'base64')})));
  await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===3&&!document.querySelector('#deck').inert);
  const rows=page.locator('.image-row'),source=rows.nth(0),untouched=rows.nth(1),portrait=rows.nth(2);
  const controls=source.locator('.position-controls'),field=name=>controls.locator(`[data-field=${name}]`);
  assert.equal(await page.locator('[data-kind=balloon]').count(),0,'opening images must not add balloons');
  assert.equal(await page.locator('#saveEdited').isDisabled(),true);
  assert.deepEqual(await source.locator('.add-actions button').evaluateAll(buttons=>buttons.map(button=>button.dataset.action)),['add-male','add-female','add-sfx','add-balloon']);
  await untouched.locator('canvas').focus();await untouched.locator('[data-action=complete]').click();
  assert.equal(await page.locator('#saveEdited').isDisabled(),true,'selection and confirmation alone must not mark an image edited');
  await source.locator('[data-action=add-balloon]').click();
  const balloon=source.locator('[data-kind=balloon]').first();
  assert.equal(await balloon.locator('[data-field=color]').inputValue(),'#ffffff');
  assert.equal(await balloon.locator('[data-field=transparency]').inputValue(),'25');
  assert.equal(await balloon.locator('[data-field=tail]').isChecked(),false);
  assert.ok(Number(await field('x').inputValue())+Number(await field('w').inputValue())/2>1000);
  assert.ok(Number(await field('y').inputValue())-Number(await field('h').inputValue())/2<0);
  assert.equal(await field('size').isVisible(),false);assert.equal(await page.locator('#savePreset').isDisabled(),true);
  assert.equal(await page.locator('#saveEdited').isEnabled(),true);
  await source.locator('[data-action=undo]').click();assert.equal(await page.locator('#saveEdited').isDisabled(),true,'undoing the first edit restores unedited status');
  await source.locator('[data-action=redo]').click();assert.equal(await page.locator('#saveEdited').isEnabled(),true);
  await field('x').fill('300');await field('y').fill('180');await field('w').fill('220');await field('h').fill('240');
  await balloon.locator('[data-field=tail]').check();
  assert.equal(await source.locator('.balloon-tail-controls').isVisible(),true);
  await field('tailX').fill('80');await field('tailY').fill('210');await field('tailAngle').fill('70');await field('tailWidth').fill('35');
  const canvas=source.locator('canvas');await canvas.scrollIntoViewIfNeeded();let rect=await canvas.boundingBox();
  let tip={x:rect.x+rect.width*380/1000,y:rect.y+rect.height*390/750};
  await page.mouse.move(tip.x,tip.y);await page.mouse.down();await page.mouse.move(tip.x+20,tip.y+12,{steps:5});await page.mouse.up();
  assert.ok(Number(await field('tailX').inputValue())>90);assert.ok(Number(await field('tailY').inputValue())>220,'tail handle updates the endpoint');
  await source.locator('[data-action=undo]').click();assert.equal(await field('tailX').inputValue(),'80');assert.equal(await field('tailY').inputValue(),'210');
  await source.locator('[data-action=redo]').click();
  await canvas.scrollIntoViewIfNeeded();rect=await canvas.boundingBox();
  const corner={x:rect.x+rect.width*410/1000,y:rect.y+rect.height*300/750};
  await page.mouse.move(corner.x,corner.y);await page.mouse.down();await page.mouse.move(corner.x+20,corner.y+20,{steps:5});await page.mouse.up();
  assert.ok(Number(await field('w').inputValue())>250);assert.ok(Number(await field('h').inputValue())>270,'bubble resize changes ellipse dimensions');
  await field('rotation').fill('15');await balloon.locator('[data-field=transparency]').fill('45');
  await source.locator('[data-action=add-male]').click();await source.locator('[data-kind=dialogue] textarea').fill('ここに台詞');
  await field('x').fill('300');await field('y').fill('180');
  await source.locator('[data-action=add-sfx]').click();
  await source.locator('[data-kind=sfx] [data-preset-select]').selectOption('sfx-tension');
  await source.locator('[data-kind=sfx] textarea').fill('ゾワッ');
  await balloon.locator('[data-field=sfxOrder]').selectOption('above');
  await page.evaluate(()=>document.fonts.ready);
  await canvas.scrollIntoViewIfNeeded();rect=await canvas.boundingBox();
  await page.mouse.click(rect.x+rect.width*.3,rect.y+rect.height*180/750);
  assert.equal(await source.locator('.layer-card.selected').getAttribute('data-kind'),'dialogue','hit testing must select dialogue above an overlapping balloon');
  const pixels=await page.evaluate(async()=>{
    const {newLayer,draw}=await import('./renderer.js');
    const image=document.createElement('canvas');image.width=100;image.height=100;image.getContext('2d').fillStyle='#0000c8';image.getContext('2d').fillRect(0,0,100,100);
    const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;const context=canvas.getContext('2d');
    const b={...newLayer('balloon',100,100),x:50,y:50,w:90,h:90,borderWidth:0};
    draw(context,image,[b]);const alpha=[...context.getImageData(50,50,1,1).data];
    b.transparency=100;draw(context,image,[]);const original=canvas.toDataURL();draw(context,image,[b]);const invisible=canvas.toDataURL();
    b.transparency=0;
    const d={...newLayer('dialogue',100,100),text:'M',x:50,y:50,w:80,h:80,size:36,outline:1,vertical:false};
    const s={...newLayer('sfx',100,100),text:'H',x:50,y:50,w:80,h:80,size:60,outline:1,color:'#ff0000',font:'sans',rotation:0,vertical:false,effect:'tension',distortion:0,roughness:0,dryInk:0,brushTails:0,skew:0,sizeVariation:0,horizontalJitter:0};
    const count=color=>{const bytes=context.getImageData(0,0,100,100).data;let n=0;for(let i=0;i<bytes.length;i+=4)if(color.every((value,j)=>bytes[i+j]===value))n++;return n;};
    draw(context,image,[b,s]);const redBehind=count([255,0,0]);b.sfxOrder='above';draw(context,image,[d,b,s]);const redAbove=count([255,0,0]),dialogue=count([17,17,17]);
    draw(context,image,[d,b]);const first=canvas.toDataURL();draw(context,image,[b,d]);const second=canvas.toDataURL();
    const t={...b,w:50,h:50,tail:true,tailX:0,tailY:50,tailWidth:20,tailAngle:90,transparency:25};
    draw(context,image,[t]);const body=[...context.getImageData(50,50,1,1).data],tail=[...context.getImageData(50,80,1,1).data];
    return {alpha,original,invisible,redBehind,redAbove,dialogue,first,second,body,tail};
  });
  assert.ok(Math.abs(pixels.alpha[0]-191)<=1&&Math.abs(pixels.alpha[2]-241)<=1,'25% transparency means 75% white opacity');
  assert.equal(pixels.original,pixels.invisible);assert.ok(pixels.redBehind>100);assert.equal(pixels.redAbove,0);assert.ok(pixels.dialogue>30);
  assert.equal(pixels.first,pixels.second,'dialogue remains above balloons in every stored order');assert.deepEqual(pixels.body,pixels.tail,'tail and ellipse must share one fill without an overlap seam');
  await page.evaluate(()=>{
    window.outputs=[];const root={getDirectoryHandle:async name=>{const output={name,files:{}};window.outputs.push(output);return {getFileHandle:async filename=>({createWritable:async()=>({write:async value=>{
      if(value instanceof Blob){const bitmap=await createImageBitmap(value),src=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(value);});output.files[filename]={width:bitmap.width,height:bitmap.height,src};bitmap.close();}
      else output.files[filename]=JSON.parse(value);
    },close:async()=>{},abort:async()=>{}})})};}};window.showDirectoryPicker=async()=>root;
  });
  await untouched.locator('canvas').focus();await page.evaluate(()=>document.fonts.ready);
  const preview=await canvas.evaluate(canvas=>canvas.toDataURL());
  await page.click('#saveEdited');await page.waitForFunction(()=>window.outputs.length===1&&window.outputs[0].files['serifu-project.json']&&!document.querySelector('#deck').inert);
  const editedOutput=await page.evaluate(()=>window.outputs[0]);const editedProject=editedOutput.files['serifu-project.json'];
  assert.ok(editedOutput.name.startsWith('serifu_'));assert.equal(Object.keys(editedOutput.files).length,2);
  assert.equal(editedProject.pages.length,1);assert.equal(editedProject.pages[0].name,'01-source.png');assert.equal(editedProject.version,4);
  const exportedBalloon=editedProject.pages[0].layers.find(layer=>layer.kind==='balloon');
  assert.equal(exportedBalloon.tail,true);assert.equal(exportedBalloon.transparency,45);assert.equal(exportedBalloon.sfxOrder,'above');
  const exportedPng=Object.values(editedOutput.files).find(file=>file.src);
  assert.equal(exportedPng.width,1000);assert.equal(exportedPng.height,750);
  const actualExport=await page.evaluate(async src=>{const img=new Image();img.src=src;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;canvas.getContext('2d').drawImage(img,0,0);return canvas.toDataURL();},exportedPng.src);
  assert.equal(actualExport,preview,'exported ellipse, tail, alpha and layering must match the unselected live preview');
  await page.click('#save');await page.waitForFunction(()=>window.outputs.length===2&&window.outputs[1].files['serifu-project.json']&&!document.querySelector('#deck').inert);
  const allOutput=await page.evaluate(()=>window.outputs[1]),allProject=allOutput.files['serifu-project.json'];
  assert.equal(Object.keys(allOutput.files).length,4);assert.equal(allProject.pages.length,3);assert.equal(allProject.pages[1].edited,false);assert.equal(allProject.pages[1].done,true);assert.equal(allProject.pages[2].edited,false);
  assert.notEqual(allOutput.name,editedOutput.name);
  await source.locator('[data-action=copy-all]').click();await portrait.locator('[data-action=paste-all]').click();
  const copiedBalloon=portrait.locator('[data-kind=balloon]').first();
  assert.equal(await copiedBalloon.locator('[data-field=transparency]').inputValue(),'45');assert.equal(await copiedBalloon.locator('[data-field=tail]').isChecked(),true);assert.equal(await copiedBalloon.locator('[data-field=sfxOrder]').inputValue(),'above');
  assert.ok(Math.abs(Number(await portrait.locator('.position-controls [data-field=tailX]').inputValue())-exportedBalloon.tailX*.5)<1e-8);
  await portrait.locator('canvas').focus();await page.keyboard.press('Control+c');await page.keyboard.press('Control+v');
  assert.equal(await portrait.locator('[data-kind=balloon]').count(),2);await page.keyboard.press('Control+z');assert.equal(await portrait.locator('[data-kind=balloon]').count(),1);
  await page.click('#saveEdited');await page.waitForFunction(()=>window.outputs.length===3&&window.outputs[2].files['serifu-project.json']&&!document.querySelector('#deck').inert);
  const filtered=await page.evaluate(()=>window.outputs[2].files['serifu-project.json']);assert.deepEqual(filtered.pages.map(page=>page.name),['01-source.png','03-portrait.png']);
  await source.locator('[data-action=cut-all]').click();assert.equal(await source.locator('.layer-card').count(),0);
  await page.click('#temporarySave');await page.waitForFunction(async()=>{const {getDraftMeta}=await import('./storage.js');const meta=await getDraftMeta();return meta?.version===4&&meta.pages[0].edited&&meta.pages[0].layers.length===0;});
  await source.locator('[data-action=undo]').click();assert.equal(await source.locator('[data-kind=balloon]').count(),1);
  await page.click('#temporarySave');await page.waitForFunction(async()=>{const {getDraftMeta}=await import('./storage.js');return (await getDraftMeta())?.pages[0].layers.some(layer=>layer.kind==='balloon');});
  await page.reload();await page.waitForSelector('#draftNotice:not([hidden])');await page.click('#restoreDraft');
  await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===3&&!document.querySelector('#deck').inert);
  assert.equal(await source.locator('[data-kind=balloon] [data-field=transparency]').inputValue(),'45');assert.equal(await source.locator('[data-kind=balloon] [data-field=tail]').isChecked(),true);
  assert.equal(await untouched.locator('.edited-badge').isVisible(),false);assert.equal(await portrait.locator('.edited-badge').isVisible(),true);
  await untouched.locator('canvas').focus();await page.evaluate(()=>document.fonts.ready);assert.equal(await canvas.evaluate(canvas=>canvas.toDataURL()),preview,'draft recovery preserves exact bubble geometry and rendering');
  await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/balloon-desktop.png'});
  await writeFile('artifacts/balloon-project.json',JSON.stringify(allProject));
  await page.reload();await page.locator('#projectInput').setInputFiles('artifacts/balloon-project.json');
  await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===3&&!document.querySelector('#deck').inert);
  assert.equal(await source.locator('[data-kind=balloon] [data-field=sfxOrder]').inputValue(),'above');assert.equal(await source.locator('[data-kind=balloon] [data-field=tail]').isChecked(),true);
  assert.equal(await untouched.locator('.edited-badge').isVisible(),false);assert.equal(await portrait.locator('.edited-badge').isVisible(),false);
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'new save and balloon controls must fit mobile widths');
  await page.screenshot({path:'artifacts/balloon-mobile.png'});assert.deepEqual(errors,[]);
  console.log('Balloon browser smoke passed: untouched/confirmed images excluded, edited-state undo and recovery, default off-image ellipse, 75% white opacity, seamless tail drag/resize, enforced dialogue layering, configurable SFX order, copy/paste across aspect ratios, preview/export parity, project/draft round-trips and mobile layout.');
}catch(error){if(page){await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/balloon-failure.png',fullPage:true}).catch(()=>{});}throw error;}
finally{await browser?.close();server.kill();}
