import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { FONT_CATALOG } from '../fonts.js';
const { chromium } = createRequire(import.meta.url)('playwright');
const port = 5187;
const server = spawn(process.execPath, ['server.mjs'], { env: { ...process.env, PORT: String(port) }, stdio: ['ignore', 'pipe', 'pipe'] });
let browser, page;
try {
  await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('Test server did not start')), 10000);
    server.stdout.once('data', () => { clearTimeout(timer); resolve(); });
    server.once('error', reject); server.stderr.on('data', chunk => process.stderr.write(chunk));
  });
  browser = await chromium.launch({ headless: true });
  page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.clock.install();
  await page.goto(`http://127.0.0.1:${port}`);
  assert.equal(await page.locator('#autosaveMinutes').inputValue(),'2');
  assert.equal(await page.locator('#autosaveEnabled').isChecked(),true);
  await page.evaluate(()=>document.fonts.ready);
  await page.click('#demo');
  await page.waitForFunction(() => document.querySelectorAll('.image-row').length === 3 && !document.querySelector('#deck').inert);
  const rows = page.locator('.image-row'), first = rows.nth(0), second = rows.nth(1);
  assert.equal(await first.locator('[data-action=copy-all]').isEnabled(),true);
  assert.equal(await first.locator('[data-action=cut-all]').isEnabled(),true);
  assert.equal(await second.locator('[data-action=paste-all]').isDisabled(),true,'batch paste requires a copied image');
  const bounds = await first.locator('.row-columns > section').evaluateAll(items => items.map(item => item.getBoundingClientRect().left));
  assert.ok(bounds[0] < bounds[1] && bounds[1] < bounds[2], 'original, dialogue and preview must appear left to right');
  assert.ok(await page.locator('textarea').evaluateAll(items=>items.every(input=>input.rows===1&&input.getBoundingClientRect().height<60)),'single-line dialogue and effects must start compact');
  const oneLineHeight=await first.locator('textarea').first().evaluate(input=>input.getBoundingClientRect().height);
  await first.locator('textarea').first().fill('一行目\n二行目\n三行目');
  assert.ok(await first.locator('textarea').first().evaluate(input=>input.getBoundingClientRect().height)>oneLineHeight*2,'newlines must grow the input');
  await first.locator('textarea').first().fill('長いセリフ'.repeat(100));
  assert.equal(await first.locator('textarea').first().evaluate(input=>input.getBoundingClientRect().height),oneLineHeight,'removing newlines must shrink the input even for long text');
  await first.locator('textarea').nth(0).fill('男性の編集テスト');
  await second.locator('textarea').nth(0).fill('二枚目の編集');
  assert.equal(await first.locator('textarea').nth(0).inputValue(), '男性の編集テスト');
  const female = await first.locator('textarea').nth(1).inputValue();
  await first.locator('[data-action=swap]').first().click();
  assert.equal(await first.locator('textarea').nth(0).inputValue(), female);
  assert.equal(await first.locator('textarea').nth(1).inputValue(), '男性の編集テスト');
  await first.locator('[data-action=undo]').click();
  assert.equal(await first.locator('textarea').nth(0).inputValue(), '男性の編集テスト');
  assert.equal(await second.locator('textarea').nth(0).inputValue(), '二枚目の編集');
  await first.locator('.layer-card').first().click();
  const selectionRect = await first.locator('canvas').boundingBox();
  await page.mouse.click(selectionRect.x + selectionRect.width * .3, selectionRect.y + selectionRect.height * 170 / 750);
  assert.equal(await first.locator('[data-action=redo]').isEnabled(), true, 'selecting text must preserve redo history');
  await first.locator('[data-action=speaker-female]').first().click();
  assert.equal(await first.locator('.layer-card').first().getAttribute('data-speaker'), 'female');
  await first.locator('[data-action=speaker-male]').first().click();
  await first.locator('textarea').first().fill('MEN');
  await first.locator('textarea').nth(1).fill('WOMEN');
  await first.locator('.layer-card').first().click();
  const pixels = await first.locator('canvas').evaluate(canvas => {
    const bytes = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data;
    const counts = { male: 0, female: 0, white: 0 };
    for (let i = 0; i < bytes.length; i += 4) {
      if (bytes[i] === 17 && bytes[i + 1] === 17 && bytes[i + 2] === 17) counts.male++;
      if (bytes[i] === 239 && bytes[i + 1] === 75 && bytes[i + 2] === 145) counts.female++;
      if (bytes[i] === 255 && bytes[i + 1] === 255 && bytes[i + 2] === 255) counts.white++;
    }
    return counts;
  });
  assert.ok(pixels.male > 100 && pixels.female > 100 && pixels.white > 100, 'black male, pink female and white keylines must be painted');
  // Preview copy/paste snapshots the whole selected layer; input shortcuts stay native.
  const shortcutCanvas=first.locator('canvas'),secondCanvas=second.locator('canvas');
  const layerCount=await first.locator('.layer-card').count();
  await first.locator('.position-controls [data-field=thickness]').fill('2.5');
  const originalX=Number(await first.locator('.position-controls [data-field=x]').inputValue());
  await shortcutCanvas.focus();await page.keyboard.press('Control+c');
  await first.locator('textarea').first().fill('コピー後に編集');
  await first.locator('.position-controls [data-field=thickness]').fill('7');
  await shortcutCanvas.focus();await page.keyboard.press('Control+v');
  assert.equal(await first.locator('.layer-card').count(),layerCount+1);
  assert.equal(await first.locator('textarea').last().inputValue(),'MEN');
  assert.equal(await first.locator('.position-controls [data-field=thickness]').inputValue(),'2.5');
  assert.equal(Number(await first.locator('.position-controls [data-field=x]').inputValue()),originalX+20);
  await page.keyboard.press('Control+z');assert.equal(await first.locator('.layer-card').count(),layerCount);
  const secondCount=await second.locator('.layer-card').count();await secondCanvas.focus();await page.keyboard.press('Meta+v');
  assert.equal(await second.locator('.layer-card').count(),secondCount+1);assert.equal(await second.locator('textarea').last().inputValue(),'MEN');
  await second.locator('textarea').last().fill('貼付け先だけ変更');assert.equal(await first.locator('textarea').first().inputValue(),'コピー後に編集');
  await secondCanvas.focus();await page.keyboard.press('Meta+z');assert.equal(await second.locator('textarea').last().inputValue(),'MEN','first undo reverts editing the pasted text');
  await page.keyboard.press('Meta+z');assert.equal(await second.locator('.layer-card').count(),secondCount,'second undo removes the paste');
  await page.keyboard.press('Meta+Shift+z');assert.equal(await second.locator('.layer-card').count(),secondCount+1,'redo restores the pasted layer');
  await page.keyboard.press('Meta+z');assert.equal(await second.locator('.layer-card').count(),secondCount);
  await first.locator('textarea').first().focus();
  const native=await first.locator('textarea').first().evaluate(input=>{
    const copy=new KeyboardEvent('keydown',{key:'c',ctrlKey:true,bubbles:true,cancelable:true}),paste=new KeyboardEvent('keydown',{key:'v',ctrlKey:true,bubbles:true,cancelable:true});
    input.dispatchEvent(copy);input.dispatchEvent(paste);return [copy.defaultPrevented,paste.defaultPrevented];
  });assert.deepEqual(native,[false,false],'text-field copy/paste must remain native');
  assert.equal(await first.locator('.layer-card').count(),layerCount);
  await first.locator('textarea').first().fill('MEN');await first.locator('.position-controls [data-field=thickness]').fill('0');
  await first.locator('.layer-card').nth(2).locator('textarea').focus();
  await first.locator('.position-controls [data-field=thickness]').fill('3.5');
  await shortcutCanvas.focus();await page.keyboard.press('Meta+c');await page.keyboard.press('Meta+v');
  assert.equal(await first.locator('.layer-card').count(),layerCount+1);
  assert.equal(await first.locator('.layer-card').last().locator('.kind-label').textContent(),'✦ 効果音');
  assert.equal(await first.locator('.position-controls [data-field=thickness]').inputValue(),'3.5');
  await page.keyboard.press('Meta+z');assert.equal(await first.locator('.layer-card').count(),layerCount);
  // Image-wide buttons work across nonadjacent images and retain an independent snapshot.
  const batchTexts=await first.locator('textarea').evaluateAll(inputs=>inputs.map(input=>input.value));
  const batchTarget=rows.nth(2),targetTexts=await batchTarget.locator('textarea').evaluateAll(inputs=>inputs.map(input=>input.value));
  await first.locator('[data-action=copy-all]').click();
  assert.equal(await batchTarget.locator('[data-action=paste-all]').isEnabled(),true);
  assert.ok((await second.locator('.batch-copy-hint').textContent()).includes('3件'));
  await first.locator('textarea').first().fill('一括コピー後に変更');
  await batchTarget.locator('[data-action=paste-all]').click();
  assert.deepEqual(await batchTarget.locator('textarea').evaluateAll(inputs=>inputs.map(input=>input.value)),[...targetTexts,...batchTexts]);
  assert.equal(await batchTarget.locator('.layer-card').nth(5).locator('.kind-label').textContent(),'✦ 効果音');
  await batchTarget.locator('textarea').last().fill('貼付け先だけ変更');
  assert.equal(await first.locator('textarea').last().inputValue(),batchTexts.at(-1));
  await batchTarget.locator('[data-action=undo]').click();
  await batchTarget.locator('[data-action=undo]').click();assert.equal(await batchTarget.locator('.layer-card').count(),3,'one undo removes the entire batch');
  await batchTarget.locator('[data-action=redo]').click();assert.equal(await batchTarget.locator('.layer-card').count(),6);
  await batchTarget.locator('[data-action=undo]').click();
  await first.locator('textarea').first().fill(batchTexts[0]);
  await first.locator('[data-action=cut-all]').click();
  assert.equal(await first.locator('.layer-card').count(),0,'batch cut removes every dialogue and effect');
  assert.equal(await first.locator('[data-action=copy-all]').isDisabled(),true);
  assert.equal(await first.locator('[data-action=cut-all]').isDisabled(),true);
  assert.equal(await first.locator('.no-layers').isVisible(),true);
  assert.equal(await first.locator('.position-controls [data-field=x]').isDisabled(),true);
  assert.ok((await second.locator('.batch-copy-hint').textContent()).includes('カット済み'));
  await batchTarget.locator('[data-action=paste-all]').click();
  assert.deepEqual(await batchTarget.locator('textarea').evaluateAll(inputs=>inputs.map(input=>input.value)),[...targetTexts,...batchTexts]);
  await batchTarget.locator('[data-action=undo]').click();assert.equal(await batchTarget.locator('.layer-card').count(),3);
  await first.locator('[data-action=undo]').click();
  assert.deepEqual(await first.locator('textarea').evaluateAll(inputs=>inputs.map(input=>input.value)),batchTexts,'one undo restores the entire cut');
  await first.locator('[data-action=redo]').click();assert.equal(await first.locator('.layer-card').count(),0);
  await first.locator('[data-action=undo]').click();
  await second.locator('[data-action=paste-all]').click();await second.locator('[data-action=paste-all]').click();
  assert.equal(await second.locator('.layer-card').count(),secondCount+layerCount*2,'the same clipboard can paste repeatedly');
  const pastedIds=await second.locator('.layer-card').evaluateAll(cards=>cards.map(card=>card.dataset.layerId));
  assert.equal(new Set(pastedIds).size,pastedIds.length,'every pasted layer needs a distinct identity');
  await second.locator('[data-action=undo]').click();await second.locator('[data-action=undo]').click();
  assert.equal(await second.locator('.layer-card').count(),secondCount);
  await first.locator('textarea').first().fill(batchTexts[0]);
  await shortcutCanvas.focus();await page.keyboard.press('Meta+v');
  assert.equal(await first.locator('.layer-card').count(),layerCount+1,'batch buttons must leave the single-layer shortcut clipboard intact');
  assert.equal(await first.locator('.layer-card').last().locator('.kind-label').textContent(),'✦ 効果音');
  await page.keyboard.press('Meta+z');
  // Actual landscape-to-portrait paste retains relative coordinates and readable glyph scaling.
  await first.locator('[data-action=copy-all]').click();
  const landscapeCoordinates=await first.locator('.position-controls').evaluate(controls=>Object.fromEntries(['x','y','w','h','size','outline','thickness'].map(field=>[field,Number(controls.querySelector(`[data-field=${field}]`).value)])));
  const portraitPng=await page.evaluate(()=>{
    const canvas=document.createElement('canvas');canvas.width=500;canvas.height=1000;
    const context=canvas.getContext('2d');context.fillStyle='#ffffff';context.fillRect(0,0,500,1000);
    return canvas.toDataURL().split(',')[1];
  });
  await page.locator('#fileInput').setInputFiles({name:'portrait.png',mimeType:'image/png',buffer:Buffer.from(portraitPng,'base64')});
  await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===4&&!document.querySelector('#deck').inert);
  const portrait=rows.nth(3);
  assert.equal(await portrait.locator('.dimensions').textContent(),'500 × 1000');
  await portrait.locator('[data-action=paste-all]').click();
  assert.deepEqual(await portrait.locator('textarea').evaluateAll(inputs=>inputs.map(input=>input.value)),batchTexts);
  const portraitCoordinates=await portrait.locator('.position-controls').evaluate(controls=>Object.fromEntries(['x','y','w','h','size','outline','thickness'].map(field=>[field,Number(controls.querySelector(`[data-field=${field}]`).value)])));
  for(const field of ['x','w','size','outline','thickness'])assert.ok(Math.abs(portraitCoordinates[field]-landscapeCoordinates[field]*.5)<1e-8,`landscape-to-portrait ${field} scales correctly`);
  for(const field of ['y','h'])assert.ok(Math.abs(portraitCoordinates[field]-landscapeCoordinates[field]*1000/750)<1e-8,`landscape-to-portrait ${field} preserves relative placement`);
  await mkdir('artifacts',{recursive:true});await portrait.screenshot({path:'artifacts/portrait-paste.png'});
  page.once('dialog',dialog=>dialog.accept());await portrait.locator('[data-action=remove]').click();
  await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===3);
  const inkCoverage=await page.evaluate(async()=>{
    const {draw,newLayer}=await import('./renderer.js');await document.fonts.load('900 80px MangaBold');
    const original=document.createElement('canvas');original.width=320;original.height=240;original.getContext('2d').fillStyle='#ffffff';original.getContext('2d').fillRect(0,0,320,240);
    const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;const ctx=canvas.getContext('2d');
    const results=[];
    for(const [kind,speaker,color] of [['dialogue','male',[17,17,17]],['dialogue','female',[239,75,145]],['sfx','male',[17,17,17]]]){
      const layer={...newLayer(kind,320,240,speaker),text:'ド',x:160,y:120,w:200,h:200,size:80,rotation:0,outline:3,effect:'tension',distortion:0,skew:0,roughness:0,dryInk:0,brushTails:0};
      const counts=[];
      for(const thickness of [-.5,0,2.5]){
        layer.thickness=thickness;draw(ctx,original,[layer]);const bytes=ctx.getImageData(0,0,320,240).data;let count=0;
        for(let i=0;i<bytes.length;i+=4)if(color.every((value,j)=>bytes[i+j]===value))count++;
        counts.push(count);
      }
      results.push({kind,speaker,counts});
    }
    return results;
  });
  for(const {kind,speaker,counts} of inkCoverage)assert.ok(counts[0]<counts[1]&&counts[1]<counts[2],`${kind}/${speaker}: numeric thickness must visibly change ink coverage`);
  await first.locator('textarea').first().focus();
  const xInput = first.locator('.position-controls [data-field=x]'), yInput = first.locator('.position-controls [data-field=y]');
  await xInput.fill('300'); await yInput.fill('170'); await yInput.blur();
  const canvas = first.locator('canvas'); await canvas.scrollIntoViewIfNeeded();
  const rect = await canvas.boundingBox(), initialX = Number(await xInput.inputValue());
  await page.mouse.move(rect.x + rect.width * .3, rect.y + rect.height * 170 / 750);
  await page.mouse.down(); await page.mouse.move(rect.x + rect.width * .35, rect.y + rect.height * 190 / 750, { steps: 6 }); await page.mouse.up();
  assert.ok(Number(await xInput.inputValue()) > initialX + 35, 'drag must update original-pixel coordinates');
  await xInput.fill('350'); await yInput.fill('350'); await yInput.blur();
  const wInput = first.locator('.position-controls [data-field=w]'), hInput = first.locator('.position-controls [data-field=h]');
  const handleRect = await canvas.boundingBox(), width = Number(await wInput.inputValue()), height = Number(await hInput.inputValue());
  const resizeX = handleRect.x + handleRect.width * (350 + width / 2) / 1000, resizeY = handleRect.y + handleRect.height * (350 + height / 2) / 750;
  await page.mouse.move(resizeX, resizeY); await page.mouse.down(); await page.mouse.move(resizeX + 15, resizeY + 15, { steps: 5 }); await page.mouse.up();
  assert.ok(Number(await wInput.inputValue()) > width, 'resize handle must update the layout width');
  const updatedHeight = Number(await hInput.inputValue()), centerX = handleRect.x + handleRect.width * .35, centerY = handleRect.y + handleRect.height * 350 / 750;
  const rotateY = centerY - handleRect.height * updatedHeight / 1500 - 24;
  await page.mouse.move(centerX, rotateY); await page.mouse.down(); await page.mouse.move(centerX + 35, rotateY + 10, { steps: 5 }); await page.mouse.up();
  assert.ok(Math.abs(Number(await first.locator('.position-controls [data-field=rotation]').inputValue())) > 5, 'rotation handle must update the angle');
  for (const effect of ['impact', 'burst', 'speed', 'rumble']) await first.locator('[data-field=effect]').selectOption(effect);
  await first.locator('[data-action=complete]').click();
  assert.ok((await page.locator('#progress').textContent()).includes('1 / 3'));
  await page.locator('#jump').selectOption(await first.getAttribute('data-page-id'));
  await mkdir('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/desktop.png' });
  assert.equal(await first.locator('.position-controls [data-field=vertical]').inputValue(),'true');
  await first.locator('textarea').first().focus();
  await first.locator('.position-controls [data-field=size]').fill('66');
  await first.locator('.position-controls [data-field=thickness]').fill('2.5');
  await first.locator('.position-controls [data-field=size]').blur();
  page.once('dialog',d=>d.accept('お気に入り縦セリフ'));await page.click('#savePreset');
  const dialoguePreset=await page.locator('#defaultDialogue').inputValue();
  await first.locator('[data-action=add-male]').click();
  assert.equal(await first.locator('.position-controls [data-field=size]').inputValue(),'66');
  assert.equal(await first.locator('.position-controls [data-field=thickness]').inputValue(),'2.5');
  assert.equal(await first.locator('.position-controls [data-field=vertical]').inputValue(),'true');
  await second.locator('[data-action=add-female]').click();
  assert.equal(await second.locator('.position-controls [data-field=size]').inputValue(),'66');
  assert.equal(await second.locator('.layer-card').last().locator('[data-preset-select]').inputValue(),dialoguePreset);
  const effectCard=first.locator('.layer-card').nth(2);await effectCard.locator('textarea').focus();
  await first.locator('.position-controls [data-field=thickness]').fill('3.5');
  await effectCard.locator('summary').click();
  assert.equal(await effectCard.locator('[data-field=sizeVariation]').inputValue(),'5');assert.equal(await effectCard.locator('[data-field=horizontalJitter]').inputValue(),'3');
  await effectCard.locator('[data-field=sizeVariation]').fill('0');await effectCard.locator('[data-field=horizontalJitter]').fill('0');
  const uniformLetters=await first.locator('canvas').evaluate(c=>c.toDataURL());
  await effectCard.locator('[data-field=sizeVariation]').fill('8.5');
  assert.notEqual(await first.locator('canvas').evaluate(c=>c.toDataURL()),uniformLetters,'letter-size variation must change the live preview');
  await effectCard.locator('[data-field=sizeVariation]').fill('0');await effectCard.locator('[data-field=horizontalJitter]').fill('3.5');
  assert.notEqual(await first.locator('canvas').evaluate(c=>c.toDataURL()),uniformLetters,'horizontal letter jitter must change the live preview independently');
  await effectCard.locator('[data-field=sizeVariation]').fill('8.5');
  const beforeBlur=await first.locator('canvas').evaluate(c=>c.toDataURL());
  await effectCard.locator('[data-field=blur]').fill('4');await effectCard.locator('[data-field=distortion]').fill('70');await effectCard.locator('[data-field=motionBlur]').fill('30');
  assert.notEqual(await first.locator('canvas').evaluate(c=>c.toDataURL()),beforeBlur,'blur/warp must change rasterized preview');
  page.once('dialog',d=>d.accept('ぼかし漫画'));await page.click('#savePreset');
  const effectPreset=await page.locator('#defaultSfx').inputValue();
  await second.locator('[data-action=add-sfx]').click();
  assert.equal(await second.locator('.layer-card').last().locator('[data-field=blur]').inputValue(),'4');
  assert.equal(await second.locator('.position-controls [data-field=thickness]').inputValue(),'3.5');
  assert.equal(await second.locator('.layer-card').last().locator('[data-field=sizeVariation]').inputValue(),'8.5');assert.equal(await second.locator('.layer-card').last().locator('[data-field=horizontalJitter]').inputValue(),'3.5');
  assert.equal(await second.locator('.layer-card').last().locator('[data-preset-select]').inputValue(),effectPreset);
  const third=rows.nth(2),tensionCard=third.locator('.layer-card').nth(2);
  await tensionCard.locator('[data-preset-select]').selectOption('sfx-tension');
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.evaluate(()=>document.fonts.check('400 110px MangaBrush')),true,'bundled Japanese brush font must load');
  await third.locator('.layer-card').nth(2).locator('summary').click();
  const tension=third.locator('.layer-card').nth(2);
  await tension.locator('[data-field=blurY]').fill('96');
  await tension.locator('[data-field=dryInk]').fill('90');
  await tension.locator('[data-field=brushTails]').fill('90');
  await tension.locator('[data-field=sizeVariation]').fill('9');await tension.locator('[data-field=horizontalJitter]').fill('4');
  await tension.locator('textarea').fill('ゾワッ');
  await third.screenshot({path:'artifacts/tension.png'});
  await third.locator('canvas').screenshot({path:'artifacts/tension-preview.png'});
  await page.locator('#defaultSfx').selectOption(effectPreset);
  const downloadPromise = page.waitForEvent('download'); await page.click('#projectSave');
  const download = await downloadPromise; await download.saveAs('artifacts/project.json');
  const project = JSON.parse(await readFile('artifacts/project.json', 'utf8'));
  assert.equal(project.version, 4); assert.equal(project.pages.length, 3); assert.equal(project.pages[0].layers[0].speaker, 'male');
  assert.equal(project.pages[0].layers[0].thickness,2.5);assert.equal(project.pages[0].layers[2].thickness,3.5);
  assert.equal(project.pages[0].layers[2].sizeVariation,8.5);assert.equal(project.pages[0].layers[2].horizontalJitter,3.5);assert.ok(Number.isInteger(project.pages[0].layers[2].glyphSeed));
  assert.equal(project.pages[2].layers[2].font,'brush');assert.equal(project.pages[2].layers[2].blurY,96);assert.equal(project.pages[2].layers[2].dryInk,90);assert.equal(project.pages[2].layers[2].brushTails,90);
  await first.locator('.layer-card').first().click();
  const expectedPreview=await third.locator('canvas').evaluate(canvas=>canvas.toDataURL());
  const repeated=await page.evaluate(async p=>{
    const {draw}=await import('./renderer.js'),img=new Image();img.src=p.src;await img.decode();
    const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;
    draw(canvas.getContext('2d'),img,p.layers);const first=canvas.toDataURL();draw(canvas.getContext('2d'),img,p.layers);const second=canvas.toDataURL();
    const {normalizeLayer}=await import('./model.js');draw(canvas.getContext('2d'),img,p.layers.map(l=>normalizeLayer(l,3)));return [first,second,canvas.toDataURL()];
  },project.pages[2]);
  assert.equal(repeated[0],repeated[1],'brush texture must stay fixed on repaint');
  assert.equal(repeated[0],expectedPreview,'export must match unselected live preview, including directional blur and dry brush');
  assert.equal(repeated[0],repeated[2],'restoring regenerated layer IDs must preserve the exact letter-size/jitter pattern');
  await second.locator('textarea').first().focus();
  const thickPreview=await first.locator('canvas').evaluate(canvas=>canvas.toDataURL());
  const thickExport=await page.evaluate(async p=>{
    const {draw}=await import('./renderer.js'),img=new Image();img.src=p.src;await img.decode();
    const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;draw(canvas.getContext('2d'),img,p.layers);return canvas.toDataURL();
  },project.pages[0]);assert.equal(thickExport,thickPreview,'dialogue and SFX thickness must match in preview and PNG export');
  await first.locator('.layer-card').nth(2).locator('textarea').focus();
  const fontSelect=first.locator('.position-controls [data-field=font]');
  assert.equal(await fontSelect.locator('option').count(),Object.keys(FONT_CATALOG).length);
  const originalFont=await fontSelect.inputValue(),fontPictures=[];
  const addedFonts=['gekifude','pop','angular','rock','hand','round','flowing','decorative','daruma','potta','yomogi','kurenai','syuku','train','dot','stick'];
  for(const key of addedFonts){
    await fontSelect.selectOption(key);await page.evaluate(()=>document.fonts.ready);
    assert.equal(await page.evaluate(async key=>{const {fontDescription}=await import('./fonts.js');return document.fonts.check(fontDescription({font:key,kind:'sfx'}).load);},key),true,`${key} must load its bundled Japanese font`);
    fontPictures.push(await first.locator('canvas').evaluate(canvas=>canvas.toDataURL()));
  }
  assert.equal(new Set(fontPictures).size,addedFonts.length,'added font choices must produce distinct letter shapes');
  await fontSelect.selectOption(originalFont);
  await page.locator('#projectInput').setInputFiles('artifacts/project.json');
  await page.waitForFunction(() => document.querySelectorAll('.image-row').length === 6 && !document.querySelector('#deck').inert);
  assert.equal(await rows.nth(3).locator('textarea').first().inputValue(), 'MEN');
  await rows.nth(3).locator('textarea').first().focus();assert.equal(await rows.nth(3).locator('.position-controls [data-field=thickness]').inputValue(),'2.5');
  assert.equal(await rows.nth(5).locator('.layer-card').nth(2).locator('[data-field=blurY]').inputValue(),'96');
  assert.equal(await rows.nth(5).locator('.layer-card').nth(2).locator('[data-field=sizeVariation]').inputValue(),'9');assert.equal(await rows.nth(5).locator('.layer-card').nth(2).locator('[data-field=horizontalJitter]').inputValue(),'4');
  const old = { version: 1, pages: [{ ...project.pages[0], layers: [{ ...project.pages[0].layers[0], kind: 'bubble', shape: 'ellipse', fill: '#ffffff', tailX: 0, tailY: 0 }] }] };
  await writeFile('artifacts/old.json', JSON.stringify(old)); await page.locator('#projectInput').setInputFiles('artifacts/old.json');
  await page.waitForFunction(() => document.querySelectorAll('.image-row').length === 7 && !document.querySelector('#deck').inert);
  assert.equal(await rows.nth(6).locator('.layer-card').first().getAttribute('data-speaker'), 'male');
  assert.equal(await rows.nth(6).locator('[data-action=delete]').isDisabled(), true);
  await page.evaluate(src => {
    window.removed = []; window.saved = {};
    const data = Uint8Array.from(atob(src.split(',')[1]), c => c.charCodeAt(0));
    const file = new File([data], 'original.png', { type: 'image/png' });
    const directory = {
      async *values() { yield { kind: 'file', getFile: async () => file }; },
      removeEntry: async name => window.removed.push(name),
      getDirectoryHandle: async () => directory,
      getFileHandle: async name => ({ createWritable: async () => ({
        write: async value => {
          if (value instanceof Blob) { const bitmap = await createImageBitmap(value); window.saved[name] = { width: bitmap.width, height: bitmap.height, bytes: value.size }; bitmap.close(); }
          else window.saved[name] = JSON.parse(value);
        }, close: async () => {}, abort: async () => {},
      }) }),
    };
    window.showDirectoryPicker = async () => directory;
  }, project.pages[0].src);
  await page.click('#open'); await page.waitForFunction(() => document.querySelectorAll('.image-row').length === 8 && !document.querySelector('#deck').inert);
  assert.equal(await rows.nth(7).locator('[data-action=copy-all]').isDisabled(),true,'an empty image has nothing to copy');
  await first.locator('[data-action=copy-all]').click();
  const savedBatchTexts=await first.locator('textarea').evaluateAll(inputs=>inputs.map(input=>input.value));
  await rows.nth(7).locator('[data-action=paste-all]').click();
  assert.deepEqual(await rows.nth(7).locator('textarea').evaluateAll(inputs=>inputs.map(input=>input.value)),savedBatchTexts,'batch paste works on an empty image');
  await rows.nth(7).locator('[data-action=cut-all]').click();
  assert.equal(await rows.nth(7).locator('.layer-card').count(),0);
  page.once('dialog', dialog => dialog.dismiss()); await rows.nth(7).locator('[data-action=delete]').click();
  assert.deepEqual(await page.evaluate(() => window.removed), []);
  page.once('dialog', dialog => dialog.accept()); await rows.nth(7).locator('[data-action=delete]').click();
  await page.waitForFunction(() => document.querySelectorAll('.image-row').length === 7 && !document.querySelector('#deck').inert);
  assert.deepEqual(await page.evaluate(() => window.removed), ['original.png']);
  await rows.nth(6).locator('[data-action=paste-all]').click();
  assert.equal(await rows.nth(6).locator('.layer-card').count(),1+savedBatchTexts.length,'batch clipboard survives deleting its source image');
  await page.click('#save'); await page.waitForFunction(() => document.querySelector('#status').textContent.includes('7 枚と編集データ'));
  const saved = await page.evaluate(() => window.saved);
  assert.equal(Object.keys(saved).length, 8); assert.equal(saved['serifu-project.json'].version, 4);
  const batchExport=saved['serifu-project.json'].pages[6].layers.slice(1);
  assert.deepEqual(batchExport.map(layer=>layer.text),savedBatchTexts);
  assert.deepEqual(batchExport.map(({id,...layer})=>layer),saved['serifu-project.json'].pages[0].layers.map(({id,...layer})=>layer),'export preserves every pasted style and position');
  for (const [name, image] of Object.entries(saved)) if (name.endsWith('.png')) { assert.equal(image.width, 1000); assert.equal(image.height, 750); }
  await page.click('#temporarySave');
  await page.waitForFunction(()=>document.querySelector('#draftStatus').textContent.includes('保存済'));
  await first.locator('textarea').first().fill('自動保存テスト');
  await page.clock.fastForward(121000);
  await page.waitForFunction(async()=>{const {getDraftMeta}=await import('./storage.js');return (await getDraftMeta())?.pages[0].layers[0].text==='自動保存テスト';});
  await page.locator('#autosaveMinutes').fill('0.1');await page.locator('#autosaveMinutes').blur();
  await first.locator('textarea').first().fill('短周期の保存');await page.clock.fastForward(6000);
  await page.waitForFunction(async()=>{const {getDraftMeta}=await import('./storage.js');return (await getDraftMeta())?.pages[0].layers[0].text==='短周期の保存';});
  await page.waitForFunction(()=>document.querySelector('#draftStatus').textContent.includes('保存済')&&!document.querySelector('#draftStatus').textContent.includes('変更あり'));
  await page.reload();await page.waitForSelector('#draftNotice:not([hidden])');
  assert.equal(await page.locator('.image-row').count(),0);
  assert.equal(await page.locator('#defaultDialogue').inputValue(),dialoguePreset);
  assert.equal(await page.locator('#defaultSfx').inputValue(),effectPreset);
  assert.equal(await page.locator('#autosaveMinutes').inputValue(),'0.1');
  await page.click('#restoreDraft');
  await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===7&&!document.querySelector('#deck').inert);
  assert.equal(await page.locator('.image-row').first().locator('textarea').first().inputValue(),'短周期の保存');
  assert.equal(await page.locator('.image-row').first().locator('.position-controls [data-field=thickness]').inputValue(),'2.5');
  assert.equal(await page.locator('.image-row').first().locator('.layer-card').nth(2).locator('[data-field=sizeVariation]').inputValue(),'8.5');assert.equal(await page.locator('.image-row').first().locator('.layer-card').nth(2).locator('[data-field=horizontalJitter]').inputValue(),'3.5');
  assert.equal(await page.locator('.image-row').nth(2).locator('.layer-card').nth(2).locator('[data-field=brushTails]').inputValue(),'90');
  assert.deepEqual(await rows.nth(6).locator('textarea').evaluateAll(inputs=>inputs.slice(1).map(input=>input.value)),savedBatchTexts,'draft recovery keeps batch copies independent of later source edits');
  assert.equal(await rows.nth(6).locator('[data-action=paste-all]').isDisabled(),true,'reloading starts with an empty clipboard');
  await page.locator('#autosaveEnabled').uncheck();
  const savedAt=await page.evaluate(async()=>{const {getDraftMeta}=await import('./storage.js');return (await getDraftMeta()).savedAt;});
  await page.locator('.image-row').first().locator('textarea').first().fill('自動保存OFF');await page.clock.fastForward(120000);
  assert.equal(await page.evaluate(async()=>{const {getDraftMeta}=await import('./storage.js');return (await getDraftMeta()).savedAt;}),savedAt,'disabled autosave must not write');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0)); await page.screenshot({ path: 'artifacts/mobile.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, 'mobile layout must not overflow horizontally');
  assert.deepEqual(errors, [], 'browser runtime errors');
  console.log('Browser smoke passed: image-wide copy/cut/paste, landscape-to-portrait placement, cut undo/redo, independent repeated batches, styles in export/draft recovery after source deletion, per-letter variation, preview shortcuts, numeric ink thickness, 19 fonts, presets, drag and original-size export.');
} catch (error) {
  if (page) { await mkdir('artifacts', { recursive: true }); await page.screenshot({ path: 'artifacts/failure.png', fullPage: true }).catch(() => {}); }
  throw error;
} finally {
  await browser?.close(); server.kill();
}
