import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {FONT_FILES} from '../fonts.js';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
const port=5198,server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','inherit']});let browser,page;
try{
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(new Error(`server exit ${code}`)));});browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${port}`);await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('#projectFormat').inputValue(),'serifu');
  const compatibility=await page.evaluate(async()=>{
    const {ImagePool}=await import('./bulk-pool.js'),{BulkTask}=await import('./bulk-task.js'),{draw,newLayer}=await import('./renderer.js'),{FONT_CATALOG,fontDescription}=await import('./fonts.js');
    const pool=new ImagePool(),task=new BulkTask('test');const c=document.createElement('canvas');c.width=640;c.height=480;c.getContext('2d').fillRect(0,0,400,400);const blob=await new Promise(r=>c.toBlob(r));
    const prepared=await pool.run('prepare-image',{blob},task,()=>{throw new Error('unexpected fallback');});
    const image=await createImageBitmap(blob),results=[];
    for(const [font,definition] of Object.entries(FONT_CATALOG)){
      const layer={...newLayer('dialogue',640,480),text:'漢字、かな「声」ABC!?',font,size:28,w:450,h:300,vertical:false};const query=fontDescription(layer).load;if(query)await document.fonts.load(query);
      const layers=[{...newLayer('balloon',640,480),x:450,y:180,w:280,h:240,tail:true},layer,{...newLayer('caption',640,480),text:'輪郭、説明。',font,w:180,h:140,textOutlineWidth:2,textOutlineColor:'#ff00cc'},{...newLayer('sfx',640,480),text:'ドーン！',font,x:360,y:340,size:44,w:240,h:140,effect:'taper',glyphSeed:123,roughness:20}];
      const output=await pool.run('render-png',{blob,width:640,height:480,layers},task,()=>{throw new Error('unexpected fallback');});
      const actual=await createImageBitmap(output),a=document.createElement('canvas'),b=document.createElement('canvas');a.width=b.width=640;a.height=b.height=480;draw(a.getContext('2d'),image,layers);b.getContext('2d').drawImage(actual,0,0);const aa=a.getContext('2d').getImageData(0,0,640,480).data,bb=b.getContext('2d').getImageData(0,0,640,480).data;let diff=0;for(let i=0;i<aa.length;i++)if(aa[i]!==bb[i])diff++;results.push({font,diff});actual.close();
    }
    image.close();task.finish();const metrics=structuredClone(pool.metrics);pool.close();return {results,prepared:{width:prepared.width,height:prepared.height},metrics};
  });
  assert.deepEqual(compatibility.prepared,{width:640,height:480});assert.deepEqual(compatibility.results.filter(r=>r.diff),[],'all font PNGs must match main-thread RGBA');assert.equal(compatibility.metrics.fallbackJobs,0);
  const imageCompatibility=await page.evaluate(async()=>{
    const {ImagePool}=await import('./bulk-pool.js'),{BulkTask}=await import('./bulk-task.js'),{imageDimensions}=await import('./image-metadata.js');const pool=new ImagePool(),task=new BulkTask('formats');const canvas=document.createElement('canvas');canvas.width=70;canvas.height=30;canvas.getContext('2d').fillRect(0,0,35,30);
    const jpeg=await new Promise(r=>canvas.toBlob(r,'image/jpeg')),bytes=new Uint8Array(await jpeg.arrayBuffer()),exif=new Uint8Array([255,225,0,34,69,120,105,102,0,0,73,73,42,0,8,0,0,0,1,0,18,1,3,0,1,0,0,0,6,0,0,0,0,0,0,0]);
    const oriented=new Blob([bytes.slice(0,2),exif,bytes.slice(2)],{type:'image/jpeg'}),gif=new Blob([Uint8Array.from(atob('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'),c=>c.charCodeAt(0))],{type:'image/gif'}),results=[];
    try{for(const blob of [jpeg,oriented,gif]){const url=URL.createObjectURL(blob),img=new Image();img.src=url;await img.decode();const prepared=await pool.run('prepare-image',{blob,dimensions:await imageDimensions(blob)},task,()=>{throw new Error('unexpected fallback');});const output=await pool.run('render-png',{blob,width:img.naturalWidth,height:img.naturalHeight,layers:[]},task,()=>{throw new Error('unexpected fallback');}),bitmap=await createImageBitmap(output),a=document.createElement('canvas'),b=document.createElement('canvas');a.width=b.width=img.naturalWidth;a.height=b.height=img.naturalHeight;a.getContext('2d').drawImage(img,0,0);b.getContext('2d').drawImage(bitmap,0,0);const aa=a.getContext('2d').getImageData(0,0,a.width,a.height).data,bb=b.getContext('2d').getImageData(0,0,b.width,b.height).data;results.push({type:blob.type,width:prepared.width,height:prepared.height,matches:aa.every((v,i)=>v===bb[i])});bitmap.close();img.src='';URL.revokeObjectURL(url);}}finally{task.finish();pool.close();}return results;
  });assert.deepEqual(imageCompatibility,[{type:'image/jpeg',width:70,height:30,matches:true},{type:'image/jpeg',width:30,height:70,matches:true},{type:'image/gif',width:1,height:1,matches:true}]);
  const ready=()=>page.waitForFunction(()=>!document.querySelector('#projectLoad').disabled);
  await page.evaluate(()=>{document.querySelector('#autosaveEnabled').click();window.addedFiles=[];window.getFiles=async()=>{const c=document.createElement('canvas');c.width=200;c.height=120;c.getContext('2d').fillRect(0,0,200,120);const blob=await new Promise(r=>c.toBlob(r));return Array.from({length:100},(_,i)=>new File([blob],`${i+1}.png`,{type:'image/png'}));};window.showDirectoryPicker=async()=>({async *values(){const files=await window.getFiles();for(const file of files)yield {kind:'file',name:file.name,getFile:async()=>{await new Promise(r=>setTimeout(r,20));return file;}};}});});
  await page.click('#open');await page.waitForFunction(()=>document.querySelectorAll('.image-row').length>0&&document.querySelector('#projectLoad').disabled);
  assert.equal(await page.locator('#deck').evaluate(n=>n.inert),false);
  const row=page.locator('.image-row').first();await row.locator('[data-action=add-male]').click();await row.locator('textarea').fill('読込中の編集');await page.click('#bulkCancel');await ready();
  const partial=await page.locator('.thumbnail').count();assert.ok(partial>0&&partial<100);assert.equal(await row.locator('textarea').inputValue(),'読込中の編集');assert.ok((await page.locator('#bulkTitle').textContent()).includes('中断'));
  // Old responses cannot enter the next operation. Fresh operation succeeds.
  await page.click('#open');await ready();assert.equal(await page.locator('.thumbnail').count(),partial+100);
  let downloading=page.waitForEvent('download');await page.click('#projectSave');const download=await downloading;assert.equal(download.suggestedFilename(),'serifu-project.serifu');await mkdir('artifacts',{recursive:true});await download.saveAs('artifacts/bulk-roundtrip.serifu');await ready();
  const imported=await browser.newPage();await imported.goto(`http://127.0.0.1:${port}`);await imported.locator('#projectInput').setInputFiles('artifacts/bulk-roundtrip.serifu');await imported.waitForFunction(()=>!document.querySelector('#projectLoad').disabled&&document.querySelectorAll('.thumbnail').length>0);assert.equal(await imported.locator('.thumbnail').count(),partial+100);assert.equal(await imported.locator('textarea').first().inputValue(),'読込中の編集');await imported.close();
  await page.evaluate(()=>{window.saved=[];window.aborted=0;window.fail=false;window.slow=false;window.showDirectoryPicker=async()=>({name:'out',getDirectoryHandle:async folder=>({getFileHandle:async name=>({createWritable:async()=>({write:async part=>{if(window.fail)throw new Error('write failure');if(window.slow)await new Promise(r=>setTimeout(r,100));},close:async()=>window.saved.push(name),abort:async()=>window.aborted++})})})});});
  await page.click('#save');await ready();const before=await page.evaluate(()=>({metrics:window.serifuMetrics,saved:window.saved}));assert.equal(before.saved.length,partial+101);assert.ok(before.saved.at(-1).endsWith('.serifu'));assert.ok(before.metrics.maxActive<=2&&before.metrics.maxResultBytes<=64*1024**2&&before.metrics.cache.bytes<=128*1024**2);
  await page.click('#save');await ready();const after=await page.evaluate(()=>window.serifuMetrics);assert.equal(after.pool.jobs,before.metrics.pool.jobs,'unchanged resave must generate zero PNG jobs');
  await page.evaluate(()=>{window.fail=true;});await page.click('#save');await ready();assert.ok((await page.locator('#bulkTitle').textContent()).includes('失敗'));assert.ok((await page.locator('#status').textContent()).includes('0 枚保存済み'));assert.ok(await page.evaluate(()=>window.aborted>0));
  await page.evaluate(()=>{window.fail=false;window.slow=true;window.saved=[];});await page.click('#save');await page.waitForFunction(()=>window.saved.length>=1);await page.click('#bulkCancel');await ready();assert.ok((await page.locator('#bulkTitle').textContent()).includes('中断'));assert.ok(await page.evaluate(()=>window.saved.length<document.querySelectorAll('.thumbnail').length));
  // Encoding failure identifies the failing PNG; a font failure keeps its own stage.
  const failedExport=await browser.newPage();await failedExport.addInitScript(()=>{const NativeWorker=window.Worker;window.Worker=class extends NativeWorker{postMessage(message,...args){if(message.kind==='render-png')queueMicrotask(()=>this.onmessage?.({data:{operationId:message.operationId,jobId:message.jobId,error:'PNG failure'}}));else super.postMessage(message,...args);}};const toBlob=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(callback,type,...args){if(type==='image/png')callback(null);else toBlob.call(this,callback,type,...args);};});await failedExport.goto(`http://127.0.0.1:${port}`);await failedExport.click('#demo');await failedExport.waitForFunction(()=>!document.querySelector('#projectLoad').disabled&&document.querySelector('#count').textContent==='3 枚');
  await failedExport.evaluate(()=>{document.querySelector('#autosaveEnabled').click();window.showDirectoryPicker=async()=>({getDirectoryHandle:async()=>({getFileHandle:async()=>({createWritable:async()=>({write:async()=>{},close:async()=>{},abort:async()=>{}})})})});});await failedExport.click('#save');await failedExport.waitForFunction(()=>!document.querySelector('#save').disabled);const pngFailure=await failedExport.evaluate(()=>window.serifuMetrics);assert.equal(pngFailure.state,'failed');assert.equal(pngFailure.errorFile,'p1_sample-1.png');assert.equal(pngFailure.pngWritten,0);assert.equal(pngFailure.projectSaved,false);
  await failedExport.evaluate(()=>{document.fonts.load=async()=>[];});await failedExport.click('#save');await failedExport.waitForFunction(()=>!document.querySelector('#save').disabled);const fontFailure=await failedExport.evaluate(()=>window.serifuMetrics);assert.equal(fontFailure.state,'failed');assert.equal(fontFailure.stage,'書体準備');assert.equal(fontFailure.errorFile,'');assert.equal(fontFailure.pngWritten,0);await failedExport.close();
  // Broken project import remains atomic.
  const count=await page.locator('.thumbnail').count();await page.locator('#projectInput').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":6,"pages":[{"name":"bad","src":"not an image","layers":[]}]}')});await ready();assert.equal(await page.locator('.thumbnail').count(),count);
  // Unsupported Worker: common fallback paths retain progress and format support.
  const fallback=await browser.newPage();await fallback.addInitScript(()=>{window.Worker=undefined;window.showDirectoryPicker=undefined;const original=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(callback,type,...args){original.call(this,blob=>type==='image/png'?setTimeout(()=>callback(blob),20):callback(blob),type,...args);};});await fallback.goto(`http://127.0.0.1:${port}`);await fallback.locator('#projectInput').setInputFiles('artifacts/bulk-roundtrip.serifu');await fallback.waitForFunction(()=>!document.querySelector('#projectLoad').disabled&&document.querySelectorAll('.thumbnail').length>0);assert.equal(await fallback.locator('.thumbnail').count(),count);assert.ok(await fallback.evaluate(()=>window.serifuMetrics.pool.fallbackJobs>0));
  const fallbackDownloads=[];fallback.on('download',download=>fallbackDownloads.push(download));await fallback.click('#save');await fallback.waitForFunction(()=>document.querySelector('#bulkStage').textContent.includes('PNG生成とZIP準備'));await fallback.evaluate(()=>document.querySelector('#bulkCancel').click());await fallback.waitForFunction(()=>!document.querySelector('#save').disabled);assert.equal(await fallback.evaluate(()=>window.serifuMetrics.state),'cancelled');assert.equal(await fallback.locator('#bulkPanel').isHidden(),true);assert.equal(fallbackDownloads.length,0,'cancelled ZIP must not download a partial archive');
  const fallbackZip=fallback.waitForEvent('download');await fallback.click('#save');await (await fallbackZip).saveAs('artifacts/brave-serifu.zip');await fallback.waitForFunction(()=>!document.querySelector('#save').disabled);assert.equal(await fallback.evaluate(()=>window.serifuMetrics.archiveEntries),count+1);assert.equal(await fallback.locator('#bulkPanel').isHidden(),true);await fallback.close();
  await page.click('#temporarySave');await page.waitForFunction(()=>document.querySelector('#draftStatus').textContent.includes('保存済'));
  const storageResult=await page.evaluate(async()=>{
    const {getDraftMeta,saveDraft}=await import('./storage.js');const previous=await getDraftMeta(),controller=new AbortController(),blob=(await window.getFiles())[0];
    const pages=Array.from({length:5},(_,i)=>({id:`cancel-${i}`,name:`cancel-${i}.png`,layers:[]}));let aborted=false;
    try{await saveDraft({version:6,pages,savedAt:Date.now()},pages.map(p=>({id:p.id,blob})),{signal:controller.signal,onProgress:()=>controller.abort(new DOMException('中断','AbortError'))});}catch(error){aborted=error.name==='AbortError';}
    return {aborted,unchanged:JSON.stringify(await getDraftMeta())===JSON.stringify(previous)};
  });assert.deepEqual(storageResult,{aborted:true,unchanged:true});
  const startupResult=await page.evaluate(async()=>{
    const {ImagePool}=await import('./bulk-pool.js'),{BulkTask}=await import('./bulk-task.js');const saved=window.Worker;let constructed=0;
    window.Worker=class{constructor(){constructed++;}postMessage(){queueMicrotask(()=>this.onerror?.({message:'crash',preventDefault(){}}));}terminate(){}};
    const pool=new ImagePool({timeout:20}),task=new BulkTask('fault');try{const first=await pool.run('prepare-image',{},task,()=>1),second=await pool.run('prepare-image',{},task,()=>2);return {constructed,first,second,disabled:pool.disabled};}finally{task.finish();pool.close();window.Worker=saved;}
  });assert.deepEqual(startupResult,{constructed:1,first:1,second:2,disabled:true});
  const jsonFallback=await page.evaluate(async()=>{
    const {projectJSON}=await import('./project-io.js');const original=window.Worker;
    // Fresh module gives an isolated JSON worker lifecycle for startup failure.
    const {projectJSON:isolated}=await import('./project-io.js?fault=1');
    window.Worker=class{postMessage(){queueMicrotask(()=>this.onerror?.({message:'JSON worker failure',preventDefault(){}}));}terminate(){}};
    try{return await isolated('parse',new Blob(['{"version":6}']));}finally{window.Worker=original;}
  });assert.deepEqual(jsonFallback,{version:6});
  // A cancelled cut retains both content and the previous undo checkpoint.
  const layerFixture=await page.evaluate(async()=>{const {newLayer}=await import('./renderer.js');const file=(await window.getFiles())[0],src=await new Promise(r=>{const reader=new FileReader();reader.onload=()=>r(reader.result);reader.readAsDataURL(file);});return {version:6,pages:[{name:'many.png',src,layers:Array.from({length:100},()=>({...newLayer('dialogue',200,120),text:'保持'}))}]};});
  await page.locator('#projectInput').setInputFiles({name:'layers.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(layerFixture))});await ready();await page.locator('.thumbnail').last().click();const lastRow=page.locator('.image-row').last();assert.equal(await lastRow.locator('.layer-card').count(),100);
  await lastRow.evaluate(row=>{row.querySelector('[data-action=cut-all]').click();document.querySelector('#bulkCancel').click();});await ready();assert.equal(await lastRow.locator('.layer-card').count(),100);assert.equal(await lastRow.locator('[data-action=undo]').isDisabled(),true);
  await page.locator('.thumbnail').first().click();
  await page.evaluate(()=>{document.querySelector('#temporarySave').click();const input=document.querySelector('.layer-card textarea');input.value='保存中の後続変更';input.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.waitForFunction(()=>document.querySelector('#draftStatus').textContent.includes('保存後の変更あり'));
  const draftCheck=await page.evaluate(async()=>{const {getDraftMeta}=await import('./storage.js');return {text:(await getDraftMeta()).pages[0].layers[0].text,metrics:window.serifuDraftMetrics};});
  assert.notEqual(draftCheck.text,'保存中の後続変更');assert.equal(draftCheck.metrics.stages['画像差分準備']>=0,true);assert.equal(draftCheck.metrics.newImages,1);
  const flagFile=await page.evaluate(async()=>{const {projectBlob}=await import('./project-io.js'),{newLayer}=await import('./renderer.js');const file=(await window.getFiles())[0],blob=await projectBlob([{name:'flags.png',file,img:{width:200,height:120},layers:[{...newLayer('dialogue',200,120),text:'状態保持'}],done:true,edited:false}],{}, {format:'serifu'});return Array.from(new Uint8Array(await blob.arrayBuffer()));});
  const flags=await browser.newPage();await flags.goto(`http://127.0.0.1:${port}`);await flags.locator('#projectInput').setInputFiles({name:'flags.serifu',mimeType:'application/octet-stream',buffer:Buffer.from(flagFile)});await flags.waitForFunction(()=>document.querySelectorAll('.thumbnail').length===1&&!document.querySelector('#projectLoad').disabled);assert.equal(await flags.locator('#saveEdited').isDisabled(),true);await flags.click('#temporarySave');await flags.waitForFunction(()=>document.querySelector('#draftStatus').textContent.includes('保存済'));await flags.reload();await flags.waitForSelector('#draftNotice:not([hidden])');await flags.click('#restoreDraft');await flags.waitForFunction(()=>document.querySelectorAll('.thumbnail').length===1&&!document.querySelector('#projectLoad').disabled);assert.equal(await flags.locator('#saveEdited').isDisabled(),true);assert.equal(await flags.locator('.image-row').evaluate(row=>row.classList.contains('done')),true);await flags.close();
  const assets=new Set(['index.html','style.css','app.js','export.js','renderer.js','model.js','balloons.js','captions.js','typography.js','ink.js','fonts.js','presets.js','storage.js','bulk-task.js','bulk-pool.js','image-worker.js','image-metadata.js','export-cache.js','project-io.js','project-worker.js','zip.js',...FONT_FILES.map(f=>'assets/fonts/'+f.file)]);
  const staticServer=createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname,relative=pathname.replace(/^\/serifu-editor\//,'')||'index.html';if(!pathname.startsWith('/serifu-editor/')||!assets.has(relative)){res.writeHead(404).end();return;}try{res.setHeader('Content-Type',relative.endsWith('.js')?'text/javascript':relative.endsWith('.css')?'text/css':relative.endsWith('.ttf')?'font/ttf':'text/html');res.end(await readFile(new URL('../_site/'+relative,import.meta.url)));}catch{res.writeHead(404).end();}});
  await new Promise(r=>staticServer.listen(0,'127.0.0.1',r));
  try{const subpath=await browser.newPage();await subpath.goto(`http://127.0.0.1:${staticServer.address().port}/serifu-editor/`);const loaded=await subpath.evaluate(async()=>{const {ImagePool}=await import('./bulk-pool.js'),{newLayer}=await import('./renderer.js');const pool=new ImagePool(),c=document.createElement('canvas');c.width=200;c.height=120;const blob=await new Promise(r=>c.toBlob(r));try{const result=await pool.run('render-png',{blob,width:200,height:120,layers:[{...newLayer('dialogue',200,120),font:'comic',text:'声'}]},null,()=>{throw new Error('Worker or font failed under subpath');});return result.size;}finally{pool.close();}});assert.ok(loaded>0);await subpath.close();}finally{await new Promise(r=>staticServer.close(r));}
  assert.deepEqual(errors,[]);await writeFile('artifacts/bulk-compatibility.json',JSON.stringify(compatibility,null,2));console.log('全21書体のWorker RGBA一致、読込中編集・中断・再開、形式往復、キャッシュ再保存、書込み失敗・中断、破損読込、Worker非対応を確認した');
}finally{await browser?.close();server.kill();}
