import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
const port=5191,server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','pipe']});
let browser,page;
try {
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Test server did not start')),10000);server.stdout.once('data',()=>{clearTimeout(timer);resolve();});server.once('error',reject);server.stderr.on('data',chunk=>process.stderr.write(chunk));});
  browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.clock.install();
  await page.goto(`http://127.0.0.1:${port}`);
  const images=await page.evaluate(()=>[[1000,750],[500,1000],[1000,750]].map(([width,height])=>{const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle='#24463a';ctx.fillRect(0,0,width,height);return canvas.toDataURL().split(',')[1];}));
  await page.locator('#fileInput').setInputFiles(images.map((base64,i)=>({name:['01-source.png','02-portrait.png','03-untouched.png'][i],mimeType:'image/png',buffer:Buffer.from(base64,'base64')})));
  await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===3&&!document.querySelector('#deck').inert);
  const rows=page.locator('.image-row'),source=rows.nth(0),portrait=rows.nth(1),untouched=rows.nth(2),controls=source.locator('.position-controls'),field=name=>controls.locator(`[data-field=${name}]`);
  assert.equal(await source.locator('[data-action=add-caption]').evaluate(button=>button.previousElementSibling.dataset.action),'add-balloon');
  assert.equal(await page.locator('[data-kind=caption]').count(),0,'captions must only be added on request');
  await source.locator('[data-action=add-caption]').click();const caption=source.locator('[data-kind=caption]').first(),text=caption.locator('textarea');
  assert.equal(await caption.locator('[data-field=color]').inputValue(),'#ffffff');assert.equal(await caption.locator('[data-field=transparency]').inputValue(),'25');assert.equal(await caption.locator('[data-field=borderColor]').inputValue(),'#000000');assert.equal(await caption.locator('[data-field=autoFit]').isChecked(),false);assert.equal(await field('size').isEnabled(),true);
  assert.equal(await field('outline').isVisible(),false);assert.equal(await field('thickness').isVisible(),false);assert.equal(await page.locator('#savePreset').isDisabled(),true);
  await source.locator('[data-action=undo]').click();assert.equal(await page.locator('#saveEdited').isDisabled(),true);await source.locator('[data-action=redo]').click();
  const body='あの頃は、まだ知らなかった。街の向こうに、長い旅が待っていた。\nこの物語は、ここから始まる。'.repeat(2);
  await text.fill(body);assert.equal(await text.getAttribute('rows'),'3');
  await field('font').selectOption('hand');await page.evaluate(()=>document.fonts.load('600 64px MangaHand'));
  await field('x').fill('500');await field('y').fill('350');await field('w').fill('280');await field('h').fill('280');await field('size').fill('32');
  const canvas=source.locator('canvas');await canvas.scrollIntoViewIfNeeded();let rect=await canvas.boundingBox();
  const corner={x:rect.x+rect.width*640/1000,y:rect.y+rect.height*490/750};
  await page.mouse.move(corner.x,corner.y);await page.mouse.down();await page.mouse.move(corner.x+25,corner.y+20,{steps:5});await page.mouse.up();
  assert.ok(Number(await field('w').inputValue())>300);assert.equal(await field('size').inputValue(),'32','manual mode must change only the box during resizing');
  await caption.locator('[data-field=autoFit]').check();assert.equal(await field('autoFit').isChecked(),true);assert.equal(await field('size').isDisabled(),true);
  const displayedSize=async()=>Number((await source.locator('.caption-fit-status').innerText()).match(/表示文字サイズ：([\d.]+)/)[1]);
  await field('w').fill('220');await field('h').fill('180');const small=await displayedSize();
  await field('w').fill('420');await field('h').fill('340');assert.ok(await displayedSize()>small,'auto-fit font must follow the available box size');
  await field('autoFit').uncheck();assert.equal(await caption.locator('[data-field=autoFit]').isChecked(),false);assert.equal(await field('size').inputValue(),'32');assert.equal(await field('size').isEnabled(),true);await field('autoFit').check();
  await caption.locator('[data-field=borderColor]').fill('#3366cc');assert.equal(await field('borderColor').inputValue(),'#3366cc');await field('textColor').fill('#8c1950');assert.equal(await caption.locator('[data-field=textColor]').inputValue(),'#8c1950');
  await caption.locator('[data-field=color]').fill('#fff5da');await field('borderWidth').fill('6');await field('padding').fill('16');
  await field('vertical').selectOption('false');assert.match(await source.locator('.caption-fit-status').innerText(),/自動追従/);await field('vertical').selectOption('true');
  await source.locator('[data-action=add-male]').click();await source.locator('[data-kind=dialogue] textarea').fill('台詞');await field('x').fill('900');await field('y').fill('680');
  await source.locator('[data-action=add-sfx]').click();await source.locator('[data-kind=sfx] textarea').fill('ドン！');
  await source.locator('[data-action=add-balloon]').click();await source.locator('[data-kind=balloon] [data-field=sfxOrder]').selectOption('above');
  await canvas.scrollIntoViewIfNeeded();rect=await canvas.boundingBox();await page.mouse.click(rect.x+rect.width*.5,rect.y+rect.height*350/750);
  assert.equal(await source.locator('.layer-card.selected').getAttribute('data-kind'),'caption','caption must stay visible and selectable above a front balloon');
  const pixels=await page.evaluate(async()=>{
    const {newLayer,draw}=await import('./renderer.js'),{captionLayout}=await import('./captions.js');
    const image=document.createElement('canvas');image.width=100;image.height=100;const base=image.getContext('2d');base.fillStyle='#0000c8';base.fillRect(0,0,100,100);
    const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;const ctx=canvas.getContext('2d'),c={...newLayer('caption',100,100),x:50,y:50,w:60,h:60,borderWidth:4,padding:4};
    draw(ctx,image,[c]);const background=[...ctx.getImageData(50,50,1,1).data],border=[...ctx.getImageData(20,50,1,1).data];
    c.text='TEST';c.vertical=false;c.textColor='#ff0000';c.autoFit=true;draw(ctx,image,[c]);const fit=captionLayout(ctx,c);let red=0;const bytes=ctx.getImageData(0,0,100,100).data;for(let i=0;i<bytes.length;i+=4)if(bytes[i]===255&&bytes[i+1]===0&&bytes[i+2]===0)red++;
    c.autoFit=false;c.size=200;draw(ctx,image,[c]);const outside=[...ctx.getImageData(5,5,1,1).data];
    return {background,border,red,fits:fit.fits,outside};
  });
  assert.ok(Math.abs(pixels.background[0]-191)<=1&&Math.abs(pixels.background[2]-241)<=1);assert.deepEqual(pixels.border,[0,0,0,255]);assert.ok(pixels.red>20,'caption font color must paint independently of dialogue colors');assert.equal(pixels.fits,true);assert.deepEqual(pixels.outside,[0,0,200,255],'oversized manual text must be clipped to the caption');
  await canvas.focus();await page.keyboard.press('Control+c');await portrait.locator('canvas').focus();await page.keyboard.press('Control+v');
  const copied=portrait.locator('[data-kind=caption]').first(),portraitField=name=>portrait.locator(`.position-controls [data-field=${name}]`);
  assert.equal(await copied.locator('textarea').inputValue(),body);assert.equal(await copied.locator('[data-field=autoFit]').isChecked(),true);assert.equal(await copied.locator('[data-field=textColor]').inputValue(),'#8c1950');assert.equal(await copied.locator('[data-field=borderColor]').inputValue(),'#3366cc');assert.equal(await portraitField('size').inputValue(),'16');assert.equal(await portraitField('w').inputValue(),'210');
  await portrait.locator('[data-action=undo]').click();assert.equal(await portrait.locator('[data-kind=caption]').count(),0);await portrait.locator('[data-action=redo]').click();
  await source.locator('[data-action=copy-all]').click();await portrait.locator('[data-action=paste-all]').click();assert.equal(await portrait.locator('.layer-card').count(),5);assert.equal(await portrait.locator('[data-kind=caption]').count(),2);
  await source.locator('[data-action=cut-all]').click();assert.equal(await source.locator('.layer-card').count(),0);await source.locator('[data-action=undo]').click();assert.equal(await source.locator('.layer-card').count(),4);
  await untouched.locator('canvas').focus();await page.evaluate(()=>document.fonts.ready);const preview=await canvas.evaluate(canvas=>canvas.toDataURL());
  let saving=page.waitForEvent('download');await source.locator('[data-action=save-image]').click();const png=await saving;assert.equal(png.suggestedFilename(),'001_01-source.png');
  const exported=await page.evaluate(async base64=>{const image=new Image();image.src=`data:image/png;base64,${base64}`;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d').drawImage(image,0,0);return {width:image.width,height:image.height,src:canvas.toDataURL()};},(await readFile(await png.path())).toString('base64'));
  assert.equal(exported.width,1000);assert.equal(exported.height,750);assert.equal(exported.src,preview,'auto-fit text, background and frame must match the unselected preview');
  await page.waitForFunction(()=>!document.querySelector('#deck').inert);
  saving=page.waitForEvent('download');await page.click('#projectSave');const jsonDownload=await saving,project=JSON.parse(await readFile(await jsonDownload.path(),'utf8'));assert.equal(project.version,5);
  const saved=project.pages[0].layers.find(layer=>layer.kind==='caption');assert.equal(saved.autoFit,true);assert.equal(saved.font,'hand');assert.equal(saved.textColor,'#8c1950');assert.equal(saved.borderColor,'#3366cc');assert.equal(saved.text,body);assert.equal(saved.size,32);
  const fitted=await page.evaluate(async layer=>{const {captionLayout}=await import('./captions.js');const canvas=document.createElement('canvas');return captionLayout(canvas.getContext('2d'),layer);},saved);assert.equal(fitted.fits,true);
  await page.waitForFunction(()=>!document.querySelector('#deck').inert);await page.click('#temporarySave');await page.waitForFunction(async()=>{const {getDraftMeta}=await import('./storage.js');const meta=await getDraftMeta();return meta?.version===5&&meta.pages[0].layers.some(layer=>layer.kind==='caption'&&layer.autoFit);});
  await page.reload();await page.waitForSelector('#draftNotice:not([hidden])');await page.click('#restoreDraft');await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===3&&!document.querySelector('#deck').inert);
  assert.equal(await source.locator('[data-kind=caption] textarea').inputValue(),body);assert.equal(await source.locator('[data-kind=caption] [data-field=autoFit]').isChecked(),true);assert.equal(await source.locator('[data-kind=caption] [data-field=borderColor]').inputValue(),'#3366cc');
  await untouched.locator('canvas').focus();await page.evaluate(()=>document.fonts.ready);assert.equal(await canvas.evaluate(canvas=>canvas.toDataURL()),preview,'draft restoration must recover exact caption geometry, font and fitting');
  await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/caption-desktop.png'});await writeFile('artifacts/caption-project.json',JSON.stringify(project));
  await page.reload();await page.locator('#projectInput').setInputFiles('artifacts/caption-project.json');await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===3&&!document.querySelector('#deck').inert);assert.equal(await source.locator('[data-kind=caption] [data-field=autoFit]').isChecked(),true);
  const legacy={...project,version:4,pages:project.pages.map(p=>({...p,layers:p.layers.filter(layer=>layer.kind!=='caption')}))};await writeFile('artifacts/caption-legacy-v4.json',JSON.stringify(legacy));await page.locator('#projectInput').setInputFiles('artifacts/caption-legacy-v4.json');await page.waitForFunction(()=>document.querySelectorAll('.image-row').length===6&&!document.querySelector('#deck').inert);assert.equal(await rows.nth(3).locator('[data-kind=balloon]').count(),1,'older version 4 projects must still import');
  await page.setViewportSize({width:390,height:844});await source.locator('[data-kind=caption] textarea').focus();await source.scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);await page.screenshot({path:'artifacts/caption-mobile.png'});
  assert.deepEqual(errors,[]);console.log('Caption browser smoke passed: manual addition, editable text/background/frame/font colors, 25% transparency, manual resize preserving font size, automatic fitting in both directions, glyph clipping, balloon ordering, portrait copy/paste, batch cut/undo, exact PNG/preview parity, project/draft recovery, legacy v4 import and mobile layout.');
}catch(error){if(page){await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/caption-failure.png',fullPage:true}).catch(()=>{});}throw error;}
finally{await browser?.close();server.kill();}
