import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const { chromium } = createRequire(import.meta.url)('playwright');
const port = 5197;
const server = spawn(process.execPath, ['server.mjs'], { env: { ...process.env, PORT: String(port) }, stdio: ['ignore', 'pipe', 'pipe'] });
let browser, page;
try {
  await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('Test server did not start')), 10000);
    server.stdout.once('data', () => { clearTimeout(timer); resolve(); });
    server.once('error', reject); server.stderr.on('data', chunk => process.stderr.write(chunk));
  });
  browser = await chromium.launch({ headless: true });
  page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${port}`);
  assert.equal(await page.locator('#pageSize').inputValue(), '50');
  const fixture = await page.evaluate(async () => {
    const { newLayer } = await import('./renderer.js');
    const canvas = document.createElement('canvas'); canvas.width = 240; canvas.height = 180;
    const ctx = canvas.getContext('2d'); ctx.fillStyle = '#303060'; ctx.fillRect(0, 0, 240, 180);
    const src = canvas.toDataURL();
    const large = document.createElement('canvas'); large.width = 512; large.height = 384;
    large.getContext('2d').drawImage(canvas, 0, 0, 512, 384);
    const caption = { ...newLayer('caption', 240, 180), text: 'OUTLINE', vertical: false, x: 120, y: 90, w: 180, h: 100, size: 22, textOutlineWidth: 3, textOutlineColor: '#00ffcc' };
    const female = { ...newLayer('dialogue', 240, 180, 'female'), text: '最後の台詞', font: 'sans' };
    return { version: 6, pages: Array.from({ length: 500 }, (_, i) => ({ name: `${String(i + 1).padStart(3, '0')}.png`, src: i === 0 ? large.toDataURL() : src, layers: i === 0 ? [caption] : i === 499 ? [female] : [], done: false, edited: false })) };
  });
  await mkdir('artifacts', { recursive: true });
  await writeFile('artifacts/paged-fixture.json', JSON.stringify(fixture));
  await page.locator('#projectInput').setInputFiles('artifacts/paged-fixture.json');
  const ready = () => page.waitForFunction(() => !document.querySelector('#deck').inert);
  await page.waitForFunction(() => document.querySelector('#count').textContent === '500 枚' && !document.querySelector('#deck').inert);
  const rows = page.locator('.image-row'), thumbs = page.locator('.thumbnail');
  const first = () => rows.first();
  assert.equal(await rows.count(), 50); assert.equal(await thumbs.count(), 500);
  assert.equal(await page.locator('#deck canvas').count(), 50);
  const thumbWidth = await thumbs.first().locator('img').evaluate(async img => { await img.decode(); return img.naturalWidth; });
  assert.equal(thumbWidth, 320);
  assert.equal(await page.locator('#viewRange').textContent(), '1–50 / 500枚');
  assert.equal(await page.locator('#previousBatch').isDisabled(), true);
  assert.equal(await first().locator('.caption-controls [data-field=textOutlineWidth]').inputValue(), '3');
  await first().locator('[data-kind=caption] [data-field=textOutlineWidth]').fill('4.5');
  assert.equal(await first().locator('.caption-controls [data-field=textOutlineWidth]').inputValue(), '4.5');
  await first().locator('.caption-controls [data-field=textOutlineColor]').fill('#ff6600');
  assert.equal(await first().locator('[data-kind=caption] [data-field=textOutlineColor]').inputValue(), '#ff6600');
  const colored = await first().locator('canvas').evaluate(canvas => {
    const pixels = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data;
    let count = 0; for (let i = 0; i < pixels.length; i += 4) if (pixels[i] === 255 && pixels[i + 1] === 102 && pixels[i + 2] === 0) count++;
    return count;
  });
  assert.ok(colored > 30, 'caption text outline must appear in Canvas pixels');
  await rows.nth(1).locator('canvas').focus(); await page.evaluate(() => document.fonts.ready);
  const preview = await first().locator('canvas').evaluate(canvas => canvas.toDataURL());
  const pngPending = page.waitForEvent('download'); await first().locator('[data-action=save-image]').click();
  const png = await pngPending;
  const savedPreview = await page.evaluate(async base64 => {
    const img = new Image(); img.src = `data:image/png;base64,${base64}`; await img.decode();
    const canvas = document.createElement('canvas'); canvas.width = img.width; canvas.height = img.height;
    canvas.getContext('2d').drawImage(img, 0, 0); return canvas.toDataURL();
  }, (await readFile(await png.path())).toString('base64'));
  assert.equal(savedPreview, preview, 'caption text outline must match the unselected preview in PNG'); await ready();
  const text = first().locator('[data-kind=caption] textarea');
  await text.fill('ABCD'); await text.press('Home'); await text.press('Delete');
  assert.equal(await text.inputValue(), 'BCD'); assert.equal(await first().locator('.layer-card').count(), 1);
  await first().locator('canvas').focus(); await page.keyboard.press('Delete');
  assert.equal(await first().locator('.layer-card').count(), 0);
  await page.keyboard.press('Control+z'); assert.equal(await text.inputValue(), 'BCD');
  assert.equal(await first().locator('.caption-controls [data-field=textOutlineWidth]').inputValue(), '4.5');
  await first().locator('[data-action=add-balloon]').click(); await first().locator('canvas').focus(); await page.keyboard.press('Delete');
  assert.equal(await first().locator('[data-kind=balloon]').count(), 0); await page.keyboard.press('Control+z');
  assert.equal(await first().locator('[data-kind=balloon]').count(), 1);
  await first().locator('[data-kind=balloon]').click(); await first().locator('canvas').focus(); await page.keyboard.press('Delete');

  await rows.nth(49).locator('[data-action=add-female]').click(); await rows.nth(49).locator('textarea').fill('境界の台詞');
  await rows.nth(49).locator('[data-action=copy-next]').click();
  assert.equal(await page.locator('#viewRange').textContent(), '51–100 / 500枚');
  assert.equal(await first().locator('textarea').inputValue(), '境界の台詞');
  await thumbs.nth(49).click(); assert.equal(await page.locator('#viewRange').textContent(), '1–50 / 500枚');
  await rows.nth(49).locator('[data-action=complete]').click();
  assert.equal(await page.locator('#viewRange').textContent(), '51–100 / 500枚');
  assert.equal(await thumbs.nth(49).locator('.thumbnail-state').textContent(), '✓ 確認済み');
  await thumbs.nth(499).click();
  assert.equal(await page.locator('#viewRange').textContent(), '451–500 / 500枚');
  assert.equal(await rows.last().locator('.page-name').textContent(), '500.png');
  assert.equal(await rows.last().evaluate(node => node.classList.contains('active')), true);
  assert.equal(await page.locator('#nextBatch').isDisabled(), true);
  await page.selectOption('#pageSize', '100'); assert.equal(await rows.count(), 100);
  assert.equal(await page.locator('#viewRange').textContent(), '401–500 / 500枚');
  await page.selectOption('#pageSize', 'all'); assert.equal(await rows.count(), 500);
  assert.equal(await page.locator('#viewRange').textContent(), '1–500 / 500枚');
  await page.selectOption('#pageSize', '50'); assert.equal(await rows.count(), 50);
  const zoom = value => page.locator('#thumbnailScale').evaluate((input, value) => { input.value = String(value); input.dispatchEvent(new Event('input', { bubbles: true })); }, value);
  await zoom(200);
  assert.equal(await page.locator('#thumbnailScaleValue').textContent(), '200%');
  const sidebarWidth = await page.locator('#thumbnailSidebar').evaluate(node => node.getBoundingClientRect().width);
  assert.ok(sidebarWidth >= 350, 'zoom must increase thumbnail/sidebar width on wide monitors');
  await page.click('#toggleThumbnails'); assert.equal(await page.locator('#thumbnailSidebar').isHidden(), true);
  await page.click('#toggleThumbnails'); assert.equal(await page.locator('#thumbnailSidebar').isVisible(), true);
  await zoom(100);

  await page.evaluate(() => {
    window.savedFiles = {};
    const root = { getDirectoryHandle: async () => ({ getFileHandle: async name => ({ createWritable: async () => ({
      write: async data => window.savedFiles[name] = data instanceof Blob ? data.size : JSON.parse(data), close: async () => {}, abort: async () => {},
    }) }) }) };
    window.showDirectoryPicker = async () => root;
  });
  await page.click('#saveEdited'); await ready();
  assert.deepEqual(await page.evaluate(() => Object.keys(window.savedFiles)), ['p001_001.png', 'p050_050.png', 'p051_051.png', 'p500_500.png', 'serifu-project.json']);
  assert.equal(await page.evaluate(() => window.savedFiles['serifu-project.json'].pages[0].layers[0].textOutlineWidth), 4.5);
  await page.evaluate(() => window.savedFiles = {}); await page.click('#save'); await ready();
  assert.equal(await page.evaluate(() => Object.keys(window.savedFiles).length), 501);
  assert.equal(await page.evaluate(() => window.savedFiles['serifu-project.json'].pages.length), 500);
  let downloading = page.waitForEvent('download'); await page.click('#projectSave');
  const json = await downloading; const project = JSON.parse(await readFile(await json.path(), 'utf8')); await ready();
  assert.equal(project.pages.length, 500);
  assert.equal(project.pages[0].layers[0].textOutlineColor, '#ff6600');
  assert.equal(project.pages[49].done, true);
  await page.selectOption('#textTarget', 'female');
  downloading = page.waitForEvent('download'); await page.click('#textSave');
  const txt = await downloading; assert.equal(await readFile(await txt.path(), 'utf8'), '\ufeff「境界の台詞」\n「境界の台詞」\n「最後の台詞」\n'); await ready();
  await page.click('#temporarySave'); await page.waitForFunction(() => document.querySelector('#draftStatus').textContent.includes('保存済'));
  await page.click('#toggleThumbnails');
  await page.reload(); await page.waitForSelector('#draftNotice:not([hidden])');
  assert.equal(await page.locator('#pageSize').inputValue(), '50');
  assert.equal(await page.locator('#thumbnailSidebar').isHidden(), true);
  await page.click('#restoreDraft'); await ready();
  assert.equal(await rows.count(), 50); assert.equal(await thumbs.count(), 500);
  assert.equal(await first().locator('.caption-controls [data-field=textOutlineWidth]').inputValue(), '4.5');
  await page.click('#toggleThumbnails');
  await thumbs.nth(49).click();
  assert.equal(await rows.nth(49).locator('textarea').inputValue(), '境界の台詞');
  assert.equal(await thumbs.nth(49).locator('.thumbnail-state').textContent(), '✓ 確認済み');
  await rows.nth(49).locator('[data-action=move-down]').click();
  assert.equal(await page.locator('#viewRange').textContent(), '51–100 / 500枚');
  assert.equal(await first().locator('.page-name').textContent(), '050.png');
  await thumbs.nth(0).click();
  await first().locator('canvas').focus(); await page.keyboard.press('Delete');
  await page.keyboard.press('Control+z');
  assert.equal(await first().locator('[data-kind=caption]').count(), 1);
  await zoom(150);
  await page.screenshot({ path: 'artifacts/paged-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'mobile layout must fit the viewport');
  await page.screenshot({ path: 'artifacts/paged-mobile.png' });
  assert.deepEqual(errors, []);
  console.log('500件の50/100/全表示、範囲境界の複製・完了・移動、サムネイル倍率・状態・表示切替、DeleteとUndo、輪郭描画・保存・復元、全体への保存とTXT出力を確認した');
} catch (error) {
  if (page) { await mkdir('artifacts', { recursive: true }); await page.screenshot({ path: 'artifacts/paged-failure.png', fullPage: true }).catch(() => {}); }
  throw error;
} finally { await browser?.close(); server.kill(); }
